#!/usr/bin/env python3
"""Write a C source that embeds a CUDA fatbin for cuModuleLoadData.

The array is 16-byte aligned (the driver reads the fatbin header in place) and
is accompanied by its byte count and SHA-256, which the library reports in its
setup agreement and receipts.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("fatbin", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check-sha256", type=Path, help="file holding the expected SHA-256 of the fatbin")
    parser.add_argument("--symbol", default="sccl_kernels_fatbin",
                        help="C name of the array; <symbol>_size and <symbol>_sha256 hold its bytes and hash")
    args = parser.parse_args()
    data = args.fatbin.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if args.check_sha256 is not None:
        expected = args.check_sha256.read_text().split()[0]
        if expected != digest:
            raise SystemExit(f"{args.fatbin}: SHA-256 {digest} differs from {expected} in {args.check_sha256}")
    lines = [
        "/* Generated by tools/embed_fatbin.py; do not edit. */",
        f"/* Source: {args.fatbin.name}, {len(data)} bytes, SHA-256 {digest}. */",
        f"const unsigned long {args.symbol}_size = {len(data)}ul;",
        f'const char {args.symbol}_sha256[] = "{digest}";',
        f"__attribute__((aligned(16))) const unsigned char {args.symbol}[] = {{",
    ]
    for start in range(0, len(data), 24):
        lines.append("  " + ",".join(str(b) for b in data[start:start + 24]) + ",")
    lines.append("};")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
