/* Generated by tools/generate_api.py from vendor/nccl.h.in (NVIDIA NCCL v2.32.3-1, Copyright (c)
 * 2015-2026 NVIDIA CORPORATION & AFFILIATES, Apache-2.0; see vendor/NCCL-LICENSE.txt). Do not edit. */
#include "internal.h"

ncclResult_t pncclMemAlloc(void** ptr, size_t size) {
  return ncclMemAlloc(ptr, size);
}

ncclResult_t pncclMemFree(void * ptr) {
  return ncclMemFree(ptr);
}

ncclResult_t pncclGetVersion(int * version) {
  return ncclGetVersion(version);
}

ncclResult_t pncclGetUniqueId(ncclUniqueId* uniqueId) {
  return ncclGetUniqueId(uniqueId);
}

ncclResult_t pncclCommInitRankConfig(ncclComm_t* comm, int nranks, ncclUniqueId commId, int rank, ncclConfig_t* config) {
  return ncclCommInitRankConfig(comm, nranks, commId, rank, config);
}

ncclResult_t pncclCommInitRank(ncclComm_t* comm, int nranks, ncclUniqueId commId, int rank) {
  return ncclCommInitRank(comm, nranks, commId, rank);
}

ncclResult_t pncclCommInitAll(ncclComm_t* comm, int ndev, const int* devlist) {
  return ncclCommInitAll(comm, ndev, devlist);
}

ncclResult_t pncclCommFinalize(ncclComm_t comm) {
  return ncclCommFinalize(comm);
}

ncclResult_t pncclCommDestroy(ncclComm_t comm) {
  return ncclCommDestroy(comm);
}

ncclResult_t pncclCommAbort(ncclComm_t comm) {
  return ncclCommAbort(comm);
}

ncclResult_t pncclCommRevoke(ncclComm_t comm, int revokeFlags) {
  return ncclCommRevoke(comm, revokeFlags);
}

ncclResult_t pncclCommSplit(ncclComm_t comm, int color, int key, ncclComm_t * newcomm, ncclConfig_t* config) {
  return ncclCommSplit(comm, color, key, newcomm, config);
}

ncclResult_t pncclCommShrink(ncclComm_t comm, int* excludeRanksList, int excludeRanksCount, ncclComm_t* newcomm, ncclConfig_t* config, int shrinkFlags) {
  return ncclCommShrink(comm, excludeRanksList, excludeRanksCount, newcomm, config, shrinkFlags);
}

ncclResult_t pncclCommGetUniqueId(ncclComm_t comm, ncclUniqueId* uniqueId) {
  return ncclCommGetUniqueId(comm, uniqueId);
}

ncclResult_t pncclCommGrow(ncclComm_t comm, int nRanks, const ncclUniqueId* uniqueId, int rank, ncclComm_t* newcomm, ncclConfig_t* config) {
  return ncclCommGrow(comm, nRanks, uniqueId, rank, newcomm, config);
}

ncclResult_t pncclCommInitRankScalable(ncclComm_t* newcomm, int nranks, int myrank, int nId, ncclUniqueId* commIds, ncclConfig_t* config) {
  return ncclCommInitRankScalable(newcomm, nranks, myrank, nId, commIds, config);
}

const char* pncclGetErrorString(ncclResult_t result) {
  return ncclGetErrorString(result);
}

const char* pncclGetLastError(ncclComm_t comm) {
  return ncclGetLastError(comm);
}

#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif
void pncclResetDebugInit(void) {
  ncclResetDebugInit();
}

#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

ncclResult_t pncclCommGetAsyncError(ncclComm_t comm, ncclResult_t * asyncError) {
  return ncclCommGetAsyncError(comm, asyncError);
}

ncclResult_t pncclCommCount(const ncclComm_t comm, int* count) {
  return ncclCommCount(comm, count);
}

ncclResult_t pncclCommCuDevice(const ncclComm_t comm, int* device) {
  return ncclCommCuDevice(comm, device);
}

ncclResult_t pncclCommUserRank(const ncclComm_t comm, int* rank) {
  return ncclCommUserRank(comm, rank);
}

ncclResult_t pncclCommRegister(const ncclComm_t comm, void* buff, size_t size, void** handle) {
  return ncclCommRegister(comm, buff, size, handle);
}

ncclResult_t pncclCommDeregister(const ncclComm_t comm, void* handle) {
  return ncclCommDeregister(comm, handle);
}

ncclResult_t pncclCommSuspend(ncclComm_t comm, int flags) {
  return ncclCommSuspend(comm, flags);
}

ncclResult_t pncclCommResume(ncclComm_t comm) {
  return ncclCommResume(comm);
}

ncclResult_t pncclCommMemStats(ncclComm_t comm, ncclCommMemStat_t stat, uint64_t* value) {
  return ncclCommMemStats(comm, stat, value);
}

ncclResult_t pncclCommWindowRegister(ncclComm_t comm, void* buff, size_t size, ncclWindow_t* win, int winFlags) {
  return ncclCommWindowRegister(comm, buff, size, win, winFlags);
}

ncclResult_t pncclCommWindowDeregister(ncclComm_t comm, ncclWindow_t win) {
  return ncclCommWindowDeregister(comm, win);
}

ncclResult_t pncclWinGetUserPtr(ncclComm_t comm, ncclWindow_t win, void** outUserPtr) {
  return ncclWinGetUserPtr(comm, win, outUserPtr);
}

ncclResult_t pncclRedOpCreatePreMulSum(ncclRedOp_t * op, void * scalar, ncclDataType_t datatype, ncclScalarResidence_t residence, ncclComm_t comm) {
  return ncclRedOpCreatePreMulSum(op, scalar, datatype, residence, comm);
}

ncclResult_t pncclRedOpDestroy(ncclRedOp_t op, ncclComm_t comm) {
  return ncclRedOpDestroy(op, comm);
}

ncclResult_t pncclReduce(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, ncclRedOp_t op, int root, ncclComm_t comm, cudaStream_t stream) {
  return ncclReduce(sendbuff, recvbuff, count, datatype, op, root, comm, stream);
}

ncclResult_t pncclBcast(void* buff, size_t count, ncclDataType_t datatype, int root, ncclComm_t comm, cudaStream_t stream) {
  return ncclBcast(buff, count, datatype, root, comm, stream);
}

ncclResult_t pncclBroadcast(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, int root, ncclComm_t comm, cudaStream_t stream) {
  return ncclBroadcast(sendbuff, recvbuff, count, datatype, root, comm, stream);
}

ncclResult_t pncclAllReduce(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, ncclRedOp_t op, ncclComm_t comm, cudaStream_t stream) {
  return ncclAllReduce(sendbuff, recvbuff, count, datatype, op, comm, stream);
}

ncclResult_t pncclReduceScatter(const void* sendbuff, void* recvbuff, size_t recvcount, ncclDataType_t datatype, ncclRedOp_t op, ncclComm_t comm, cudaStream_t stream) {
  return ncclReduceScatter(sendbuff, recvbuff, recvcount, datatype, op, comm, stream);
}

ncclResult_t pncclAllGather(const void* sendbuff, void* recvbuff, size_t sendcount, ncclDataType_t datatype, ncclComm_t comm, cudaStream_t stream) {
  return ncclAllGather(sendbuff, recvbuff, sendcount, datatype, comm, stream);
}

ncclResult_t pncclAlltoAll(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, ncclComm_t comm, cudaStream_t stream) {
  return ncclAlltoAll(sendbuff, recvbuff, count, datatype, comm, stream);
}

ncclResult_t pncclGather(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, int root, ncclComm_t comm, cudaStream_t stream) {
  return ncclGather(sendbuff, recvbuff, count, datatype, root, comm, stream);
}

ncclResult_t pncclScatter(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, int root, ncclComm_t comm, cudaStream_t stream) {
  return ncclScatter(sendbuff, recvbuff, count, datatype, root, comm, stream);
}

ncclResult_t pncclAllReduceConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, ncclRedOp_t op, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  return ncclAllReduceConfig(sendbuff, recvbuff, count, datatype, op, comm, stream, config);
}

ncclResult_t pncclBroadcastConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, int root, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  return ncclBroadcastConfig(sendbuff, recvbuff, count, datatype, root, comm, stream, config);
}

ncclResult_t pncclReduceConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, ncclRedOp_t op, int root, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  return ncclReduceConfig(sendbuff, recvbuff, count, datatype, op, root, comm, stream, config);
}

ncclResult_t pncclAllGatherConfig(const void* sendbuff, void* recvbuff, size_t sendcount, ncclDataType_t datatype, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  return ncclAllGatherConfig(sendbuff, recvbuff, sendcount, datatype, comm, stream, config);
}

ncclResult_t pncclReduceScatterConfig(const void* sendbuff, void* recvbuff, size_t recvcount, ncclDataType_t datatype, ncclRedOp_t op, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  return ncclReduceScatterConfig(sendbuff, recvbuff, recvcount, datatype, op, comm, stream, config);
}

ncclResult_t pncclAlltoAllConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  return ncclAlltoAllConfig(sendbuff, recvbuff, count, datatype, comm, stream, config);
}

ncclResult_t pncclGatherConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, int root, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  return ncclGatherConfig(sendbuff, recvbuff, count, datatype, root, comm, stream, config);
}

ncclResult_t pncclScatterConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, int root, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  return ncclScatterConfig(sendbuff, recvbuff, count, datatype, root, comm, stream, config);
}

ncclResult_t pncclSend(const void* sendbuff, size_t count, ncclDataType_t datatype, int peer, ncclComm_t comm, cudaStream_t stream) {
  return ncclSend(sendbuff, count, datatype, peer, comm, stream);
}

ncclResult_t pncclRecv(void* recvbuff, size_t count, ncclDataType_t datatype, int peer, ncclComm_t comm, cudaStream_t stream) {
  return ncclRecv(recvbuff, count, datatype, peer, comm, stream);
}

ncclResult_t pncclPutSignal(const void* localbuff, size_t count, ncclDataType_t datatype, int peer, ncclWindow_t peerWin, size_t peerWinOffset, int sigIdx, int ctx, unsigned int flags, ncclComm_t comm, cudaStream_t stream) {
  return ncclPutSignal(localbuff, count, datatype, peer, peerWin, peerWinOffset, sigIdx, ctx, flags, comm, stream);
}

ncclResult_t pncclSignal(int peer, int sigIdx, int ctx, unsigned int flags, ncclComm_t comm, cudaStream_t stream) {
  return ncclSignal(peer, sigIdx, ctx, flags, comm, stream);
}

ncclResult_t pncclWaitSignal(int nDesc, ncclWaitSignalDesc_t* signalDescs, ncclComm_t comm, cudaStream_t stream) {
  return ncclWaitSignal(nDesc, signalDescs, comm, stream);
}

ncclResult_t pncclGroupStart(void) {
  return ncclGroupStart();
}

ncclResult_t pncclGroupEnd(void) {
  return ncclGroupEnd();
}

ncclResult_t pncclGroupSimulateEnd(ncclSimInfo_t* simInfo) {
  return ncclGroupSimulateEnd(simInfo);
}

ncclResult_t pncclSetEncryption(const ncclEncryptionConfig_t* config) {
  return ncclSetEncryption(config);
}

ncclResult_t pncclParamBind(ncclParamHandle_t* out, const char* key) {
  return ncclParamBind(out, key);
}

ncclResult_t pncclParamGetI8(ncclParamHandle_t h, int8_t* out) {
  return ncclParamGetI8(h, out);
}

ncclResult_t pncclParamGetI16(ncclParamHandle_t h, int16_t* out) {
  return ncclParamGetI16(h, out);
}

ncclResult_t pncclParamGetI32(ncclParamHandle_t h, int32_t* out) {
  return ncclParamGetI32(h, out);
}

ncclResult_t pncclParamGetI64(ncclParamHandle_t h, int64_t* out) {
  return ncclParamGetI64(h, out);
}

ncclResult_t pncclParamGetU8(ncclParamHandle_t h, uint8_t* out) {
  return ncclParamGetU8(h, out);
}

ncclResult_t pncclParamGetU16(ncclParamHandle_t h, uint16_t* out) {
  return ncclParamGetU16(h, out);
}

ncclResult_t pncclParamGetU32(ncclParamHandle_t h, uint32_t* out) {
  return ncclParamGetU32(h, out);
}

ncclResult_t pncclParamGetU64(ncclParamHandle_t h, uint64_t* out) {
  return ncclParamGetU64(h, out);
}

ncclResult_t pncclParamGetStr(ncclParamHandle_t h, const char** out) {
  return ncclParamGetStr(h, out);
}

ncclResult_t pncclParamGet(ncclParamHandle_t h, void* out, int maxLen, int* len) {
  return ncclParamGet(h, out, maxLen, len);
}

ncclResult_t pncclParamGetParameter(const char* key, const char** value, int* valueLen) {
  return ncclParamGetParameter(key, value, valueLen);
}

ncclResult_t pncclParamGetAllParameterKeys(const char*** table, int* tableLen) {
  return ncclParamGetAllParameterKeys(table, tableLen);
}

void pncclParamDumpAll(void) {
  ncclParamDumpAll();
}

