/* Generated by tools/generate_api.py from vendor/nccl.h.in (NVIDIA NCCL v2.32.3-1, Copyright (c)
 * 2015-2026 NVIDIA CORPORATION & AFFILIATES, Apache-2.0; see vendor/NCCL-LICENSE.txt). Do not edit. */
#include "internal.h"

ncclResult_t ncclCommShrink(ncclComm_t comm, int* excludeRanksList, int excludeRanksCount, ncclComm_t* newcomm, ncclConfig_t* config, int shrinkFlags) {
  (void)comm;
  (void)excludeRanksList;
  (void)excludeRanksCount;
  (void)newcomm;
  (void)config;
  (void)shrinkFlags;
  return sccl_unsupported("ncclCommShrink");
}

ncclResult_t ncclCommGetUniqueId(ncclComm_t comm, ncclUniqueId* uniqueId) {
  (void)comm;
  (void)uniqueId;
  return sccl_unsupported("ncclCommGetUniqueId");
}

ncclResult_t ncclCommGrow(ncclComm_t comm, int nRanks, const ncclUniqueId* uniqueId, int rank, ncclComm_t* newcomm, ncclConfig_t* config) {
  (void)comm;
  (void)nRanks;
  (void)uniqueId;
  (void)rank;
  (void)newcomm;
  (void)config;
  return sccl_unsupported("ncclCommGrow");
}

ncclResult_t ncclCommInitRankScalable(ncclComm_t* newcomm, int nranks, int myrank, int nId, ncclUniqueId* commIds, ncclConfig_t* config) {
  (void)newcomm;
  (void)nranks;
  (void)myrank;
  (void)nId;
  (void)commIds;
  (void)config;
  return sccl_unsupported("ncclCommInitRankScalable");
}

void ncclResetDebugInit(void) {
  (void)sccl_unsupported("ncclResetDebugInit");
}

ncclResult_t ncclCommSuspend(ncclComm_t comm, int flags) {
  (void)comm;
  (void)flags;
  return sccl_unsupported("ncclCommSuspend");
}

ncclResult_t ncclCommResume(ncclComm_t comm) {
  (void)comm;
  return sccl_unsupported("ncclCommResume");
}

ncclResult_t ncclCommMemStats(ncclComm_t comm, ncclCommMemStat_t stat, uint64_t* value) {
  (void)comm;
  (void)stat;
  (void)value;
  return sccl_unsupported("ncclCommMemStats");
}

ncclResult_t ncclRedOpCreatePreMulSum(ncclRedOp_t * op, void * scalar, ncclDataType_t datatype, ncclScalarResidence_t residence, ncclComm_t comm) {
  if (op) *op = (ncclRedOp_t)ncclNumOps;
  (void)scalar;
  (void)datatype;
  (void)residence;
  (void)comm;
  return sccl_unsupported("ncclRedOpCreatePreMulSum");
}

ncclResult_t ncclRedOpDestroy(ncclRedOp_t op, ncclComm_t comm) {
  (void)op;
  (void)comm;
  return sccl_unsupported("ncclRedOpDestroy");
}

ncclResult_t ncclAllReduceConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, ncclRedOp_t op, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  (void)sendbuff;
  (void)recvbuff;
  (void)count;
  (void)datatype;
  (void)op;
  (void)comm;
  (void)stream;
  (void)config;
  return sccl_unsupported("ncclAllReduceConfig");
}

ncclResult_t ncclBroadcastConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, int root, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  (void)sendbuff;
  (void)recvbuff;
  (void)count;
  (void)datatype;
  (void)root;
  (void)comm;
  (void)stream;
  (void)config;
  return sccl_unsupported("ncclBroadcastConfig");
}

ncclResult_t ncclReduceConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, ncclRedOp_t op, int root, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  (void)sendbuff;
  (void)recvbuff;
  (void)count;
  (void)datatype;
  (void)op;
  (void)root;
  (void)comm;
  (void)stream;
  (void)config;
  return sccl_unsupported("ncclReduceConfig");
}

ncclResult_t ncclAllGatherConfig(const void* sendbuff, void* recvbuff, size_t sendcount, ncclDataType_t datatype, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  (void)sendbuff;
  (void)recvbuff;
  (void)sendcount;
  (void)datatype;
  (void)comm;
  (void)stream;
  (void)config;
  return sccl_unsupported("ncclAllGatherConfig");
}

ncclResult_t ncclReduceScatterConfig(const void* sendbuff, void* recvbuff, size_t recvcount, ncclDataType_t datatype, ncclRedOp_t op, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  (void)sendbuff;
  (void)recvbuff;
  (void)recvcount;
  (void)datatype;
  (void)op;
  (void)comm;
  (void)stream;
  (void)config;
  return sccl_unsupported("ncclReduceScatterConfig");
}

ncclResult_t ncclAlltoAllConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  (void)sendbuff;
  (void)recvbuff;
  (void)count;
  (void)datatype;
  (void)comm;
  (void)stream;
  (void)config;
  return sccl_unsupported("ncclAlltoAllConfig");
}

ncclResult_t ncclGatherConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, int root, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  (void)sendbuff;
  (void)recvbuff;
  (void)count;
  (void)datatype;
  (void)root;
  (void)comm;
  (void)stream;
  (void)config;
  return sccl_unsupported("ncclGatherConfig");
}

ncclResult_t ncclScatterConfig(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype, int root, ncclComm_t comm, cudaStream_t stream, const ncclCollConfig_t* config) {
  (void)sendbuff;
  (void)recvbuff;
  (void)count;
  (void)datatype;
  (void)root;
  (void)comm;
  (void)stream;
  (void)config;
  return sccl_unsupported("ncclScatterConfig");
}

ncclResult_t ncclPutSignal(const void* localbuff, size_t count, ncclDataType_t datatype, int peer, ncclWindow_t peerWin, size_t peerWinOffset, int sigIdx, int ctx, unsigned int flags, ncclComm_t comm, cudaStream_t stream) {
  (void)localbuff;
  (void)count;
  (void)datatype;
  (void)peer;
  (void)peerWin;
  (void)peerWinOffset;
  (void)sigIdx;
  (void)ctx;
  (void)flags;
  (void)comm;
  (void)stream;
  return sccl_unsupported("ncclPutSignal");
}

ncclResult_t ncclSignal(int peer, int sigIdx, int ctx, unsigned int flags, ncclComm_t comm, cudaStream_t stream) {
  (void)peer;
  (void)sigIdx;
  (void)ctx;
  (void)flags;
  (void)comm;
  (void)stream;
  return sccl_unsupported("ncclSignal");
}

ncclResult_t ncclWaitSignal(int nDesc, ncclWaitSignalDesc_t* signalDescs, ncclComm_t comm, cudaStream_t stream) {
  (void)nDesc;
  (void)signalDescs;
  (void)comm;
  (void)stream;
  return sccl_unsupported("ncclWaitSignal");
}

ncclResult_t ncclGroupSimulateEnd(ncclSimInfo_t* simInfo) {
  (void)simInfo;
  return sccl_unsupported("ncclGroupSimulateEnd");
}

ncclResult_t ncclSetEncryption(const ncclEncryptionConfig_t* config) {
  (void)config;
  return sccl_unsupported("ncclSetEncryption");
}

ncclResult_t ncclParamBind(ncclParamHandle_t* out, const char* key) {
  (void)out;
  (void)key;
  return sccl_unsupported("ncclParamBind");
}

ncclResult_t ncclParamGetI8(ncclParamHandle_t h, int8_t* out) {
  (void)h;
  (void)out;
  return sccl_unsupported("ncclParamGetI8");
}

ncclResult_t ncclParamGetI16(ncclParamHandle_t h, int16_t* out) {
  (void)h;
  (void)out;
  return sccl_unsupported("ncclParamGetI16");
}

ncclResult_t ncclParamGetI32(ncclParamHandle_t h, int32_t* out) {
  (void)h;
  (void)out;
  return sccl_unsupported("ncclParamGetI32");
}

ncclResult_t ncclParamGetI64(ncclParamHandle_t h, int64_t* out) {
  (void)h;
  (void)out;
  return sccl_unsupported("ncclParamGetI64");
}

ncclResult_t ncclParamGetU8(ncclParamHandle_t h, uint8_t* out) {
  (void)h;
  (void)out;
  return sccl_unsupported("ncclParamGetU8");
}

ncclResult_t ncclParamGetU16(ncclParamHandle_t h, uint16_t* out) {
  (void)h;
  (void)out;
  return sccl_unsupported("ncclParamGetU16");
}

ncclResult_t ncclParamGetU32(ncclParamHandle_t h, uint32_t* out) {
  (void)h;
  (void)out;
  return sccl_unsupported("ncclParamGetU32");
}

ncclResult_t ncclParamGetU64(ncclParamHandle_t h, uint64_t* out) {
  (void)h;
  (void)out;
  return sccl_unsupported("ncclParamGetU64");
}

ncclResult_t ncclParamGetStr(ncclParamHandle_t h, const char** out) {
  (void)h;
  (void)out;
  return sccl_unsupported("ncclParamGetStr");
}

ncclResult_t ncclParamGet(ncclParamHandle_t h, void* out, int maxLen, int* len) {
  (void)h;
  (void)out;
  (void)maxLen;
  (void)len;
  return sccl_unsupported("ncclParamGet");
}

ncclResult_t ncclParamGetParameter(const char* key, const char** value, int* valueLen) {
  (void)key;
  (void)value;
  (void)valueLen;
  return sccl_unsupported("ncclParamGetParameter");
}

ncclResult_t ncclParamGetAllParameterKeys(const char*** table, int* tableLen) {
  (void)table;
  (void)tableLen;
  return sccl_unsupported("ncclParamGetAllParameterKeys");
}

void ncclParamDumpAll(void) {
  (void)sccl_unsupported("ncclParamDumpAll");
}

