"""Verify external runtime package inventories without Docker or a GPU."""

import importlib.util
import json
import os
from pathlib import Path

import pytest


spec = importlib.util.spec_from_file_location(
    "external_base", Path(__file__).with_name("external_base.py")
)
adapter = importlib.util.module_from_spec(spec)
spec.loader.exec_module(adapter)


@pytest.fixture
def installed_packages(tmp_path, monkeypatch):
    site = tmp_path / "site-packages"
    files = {}
    for package in adapter.PACKAGE_NAMES:
        root = site / package
        root.mkdir(parents=True)
        for name, data in (("__init__.py", b"# package\n"), ("native.so", b"native")):
            path = root / name
            path.write_bytes(data)
            files[str(path)] = adapter.sha(path)
    receipt = tmp_path / "installed.json"
    receipt.write_text(json.dumps({
        "schema": "sparkring-external-installed/v1",
        "composition_sha256": "a" * 64,
        "sources": {},
        "files": files,
        "distribution_records": {},
        "removed_files": [],
        "symlinks": {},
        "versions": {},
    }))
    monkeypatch.setattr(adapter, "SITE", str(site) + os.sep)
    monkeypatch.setattr(adapter, "RECEIPT", receipt)
    return site


@pytest.mark.parametrize("package", sorted(adapter.PACKAGE_NAMES))
@pytest.mark.parametrize("addition", ("unexpected.py", "unexpected.so"))
def test_verify_rejects_unrecorded_package_files(installed_packages, package, addition):
    adapter.verify()
    (installed_packages / package / addition).write_bytes(b"unrecorded payload")

    with pytest.raises(ValueError, match="Installed package inventory differs: " + package):
        adapter.verify()


def test_verify_ignores_generated_bytecode(installed_packages):
    for package in adapter.PACKAGE_NAMES:
        cache = installed_packages / package / "__pycache__"
        cache.mkdir()
        (cache / "__init__.cpython-312.pyc").write_bytes(b"generated bytecode")

    result = adapter.verify()

    assert result["files_verified"] == 6
    assert result["serving_qualified"] is False
