"""Local node identity, approved boot configuration, observations and fabric upkeep.

Only the node CLI runs privileged operations, including the host agent it
runs (``sparkring node agent``). The agent observes, adds the approved fabric
routes and relay table objects that are missing and sets the approved
per-interface fabric settings that differ (``restore_fabric``); it changes
nothing else.
No listening control socket or sudoers rule is installed; setup uses the
operator's existing SSH/sudo authority.
"""
import ipaddress
import json
import os
from pathlib import Path, PurePosixPath
import re
import socket
import subprocess
import sys
import time
import uuid

from runtime.common import distribution, fabric_layout
from runtime.host import control, relays as relay_table
from runtime.host.discovery import target
from scripts import hairpin_setting
from scripts.deploy_inventory import _collect_local, _request, gid_index_hint, validate_inventory

ROOT = Path(__file__).resolve().parents[2]
# Generated by packaging/debian/sparkring-hairpin-mesh-check for every mesh unit file.
MESH_START_CHECK = "10-sparkring-hairpin.conf"
MESH_UNIT_PATTERNS = ("sparkring-mesh.service", "sparkring-*-mesh.service")
HAIRPIN_REMEDY = "on Node A: sudo sparkring hairpin"
# Seconds after which a tunnel peer's latest handshake means it has no working
# path; control.HANDSHAKE_STALE explains the value.
HANDSHAKE_STALE = control.HANDSHAKE_STALE
# The characters of an error line that a status document carries.
ERROR_TEXT = 300
# The boot service that restores the approved fabric (routes, forwarding settings and rules, relay table).
FABRIC_UNIT = "sparkring-fabric.service"
# The service that runs the relay table's marker processes (runtime/host/relays.py).
MARKER_UNIT = relay_table.MARKER_UNIT
# Fields of a fabric record that a setup of the same Sparks may replace in place.
REFRESHED_FIELDS = ("layout", "relays")
# Seconds between the agent's observations, and so between its route and setting checks.
AGENT_INTERVAL = 30
# Per-interface IPv4 settings (net.ipv4.conf.IFACE.NAME) of each fabric function
# that the fabric record lets forward. Per-interface forwarding avoids enabling
# routing on management NICs. The kernel validates sources with the larger of
# conf/all/rp_filter and the interface's value, so with Ubuntu's default
# all.rp_filter=2 the interface's 0 leaves loose validation in effect.
FORWARDING_SETTINGS = (("forwarding", "1"), ("rp_filter", "0"))


class HairpinNotInEffect(ValueError):
    """A fabric function of a Spark that relays between its cables lacks the ConnectX hairpin setting."""

    next_action = HAIRPIN_REMEDY


def location(root, name):
    path = Path(root) / str(name).lstrip("/")
    if any(p.is_symlink() for p in (path, *path.parents)):
        raise ValueError("Node state path contains a symlink: " + str(path))
    return path


def read(root, name):
    return json.loads(location(root, name).read_text(encoding="utf-8"))


def save(root, name, value, mode=0o644):
    path = location(root, name)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".writing")
    location(root, temporary.relative_to(Path(root)))
    with temporary.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(json.dumps(value, indent=2) + "\n")
    temporary.chmod(mode)
    temporary.replace(path)


def call(argv, *, run=subprocess.run, accepted=(0,)):
    result = run(argv, capture_output=True, text=True, timeout=90)
    if result.returncode not in accepted:
        raise RuntimeError(" ".join(argv[:4]) + ": " + result.stderr.strip())
    return result


def initialize(root="/"):
    path = location(root, "/etc/sparkring/node.json")
    if path.exists():
        document = read(root, "/etc/sparkring/node.json")
        uuid.UUID(document["node_id"])
    else:
        document = {"schema": "sparkring-node/v1", "node_id": str(uuid.uuid4())}
        save(root, "/etc/sparkring/node.json", document)
    # Avahi advertises candidates; SSH host keys establish their identity.
    service = location(root, "/etc/avahi/services/sparkring.service")
    service.parent.mkdir(parents=True, exist_ok=True)
    service.write_text('''<?xml version="1.0" standalone="no"?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group><name replace-wildcards="yes">SparkRing on %h</name>
<service><type>_sparkring._tcp</type><port>22</port>
<txt-record>protocol=ssh</txt-record></service></service-group>
''', encoding="utf-8")
    return document


def inspect(rank, ssh_target, management, witness, *, root="/", collect=_collect_local, run=subprocess.run):
    target(ssh_target)
    if management != ssh_target.split("@", 1)[1] or management == witness:
        raise ValueError("Use the host management IP and another Spark as its route witness")
    facts = collect(_request(rank, ssh_target, management, (), witness))
    validate_inventory(facts, require_ready=True)
    lldp = json.loads(call(["lldpctl", "-f", "json"], run=run).stdout)
    identity = read(root, "/etc/sparkring/node.json")
    record = distribution.installed(ROOT)
    # hairpin imports this module; the function states come from the collected
    # facts, so the status adds no devlink call.
    from runtime.host import hairpin
    return {"schema": "sparkring-node-inventory/v1", "node_id": identity["node_id"],
            "hostname": socket.gethostname(), "revision": record["revision"] if record else None,
            "facts": facts, "lldp": lldp, "hairpin": hairpin.status(facts=facts, root=root, run=run)}


def record_layout(config):
    """The fabric layout of a fabric record: its ``layout``, or a pair or four-Spark cycle by ``size``."""
    if config.get("layout") is not None:
        value = fabric_layout.checked(config["layout"])
        if value["size"] != config.get("size"):
            raise ValueError("Fabric record size differs from its layout")
        return value
    return fabric_layout.legacy(config.get("size"))


def relays_hairpin(config):
    """Whether this Spark relays between its cables, so its functions need the ConnectX hairpin setting."""
    value = record_layout(config)
    return fabric_layout.relayed(value) and fabric_layout.forwards(value, config["rank"])


def mesh_ring(config):
    """Whether the record is a four-Spark cycle, the only layout with per-deployment mesh services."""
    return record_layout(config) == fabric_layout.layout(fabric_layout.CYCLE, 4)


def validate(config):
    if config.get("schema") != "sparkring-fabric-state/v1" or not re.fullmatch("[0-9a-f]{64}", config.get("cluster_id", "")):
        raise ValueError("Invalid approved fabric state")
    uuid.UUID(config["node_id"])
    if (type(config.get("size")) is not int or not fabric_layout.MIN_SPARKS <= config["size"] <= fabric_layout.MAX_SPARKS
            or type(config["rank"]) is not int or config["rank"] not in range(config["size"])):
        raise ValueError("Invalid rank or size")
    layout = record_layout(config)
    target(config["ssh_target"])
    management = config["management"]
    for key in ("address", "witness"):
        address = ipaddress.IPv4Address(management[key])
        if address.is_multicast or address.is_unspecified or address.is_loopback:
            raise ValueError("Invalid management address")
    if management["address"] == management["witness"]:
        raise ValueError("Management witness must be another host")
    ports = config["interfaces"]
    roles = fabric_layout.roles(layout, config["rank"])
    count = len(roles)
    if (len(ports) != count or len({p["netdev"] for p in ports}) != count
            or sorted(p.get("role") for p in ports) != sorted(roles)):
        raise ValueError("Invalid fabric interfaces")
    nets = {}
    for p in ports:
        if not re.fullmatch(r"[A-Za-z0-9_-]{1,15}", p["netdev"]) or p["netdev"] == management["interface"]:
            raise ValueError("Invalid data interface or management interface selected")
        if not re.fullmatch(r"(?:[0-9a-f]{2}:){5}[0-9a-f]{2}", p["mac"]):
            raise ValueError("Expected data interface MAC")
        endpoint = ipaddress.IPv4Interface(p["address"])
        if endpoint.network.prefixlen != 24 or any(ipaddress.ip_address(management[k]) in endpoint.network for k in ("address", "witness")):
            raise ValueError("Fabric must use /24 subnets separate from management")
        nets[p["netdev"]] = endpoint.network
    if len(set(nets.values())) != count:
        raise ValueError("Fabric functions require separate subnets")
    for route in config["routes"]:
        network = ipaddress.IPv4Network(route["destination"])
        if (network.prefixlen != 24 or route["dev"] not in nets
                or ipaddress.IPv4Address(route["via"]) not in nets[route["dev"]]
                or any(ipaddress.ip_address(management[k]) in network for k in ("address", "witness"))
                or any(network.overlaps(n) for n in nets.values())):
            raise ValueError("Route must reach a remote fabric /24 through a verified data interface")
    if any(len(pair) != 2 or pair[0] == pair[1] or not set(pair) <= nets.keys() for pair in config["forwarding"]):
        raise ValueError("Forwarding must stay between distinct data interfaces")
    if layout["shape"] == fabric_layout.PAIR and (config["routes"] or config["forwarding"]):
        raise ValueError("Pair requires no routed fabric")
    if config.get("relays") is not None:
        relay_table.validate_section(config["relays"], config)
    return config


def observe(config, *, collect=_collect_local):
    validate(config)
    m = config["management"]
    facts = collect(_request(config["rank"], config["ssh_target"], m["address"], (), m["witness"]))
    management = facts["management"]
    if (management.get("error") or management.get("interface") != m["interface"]
            or (management.get("route_to_controller") or {}).get("dev") != m["interface"]):
        raise ValueError("Independent management path changed")
    interfaces = {i["name"]: i for i in facts["interfaces"]}
    functions = {i["device"]: i for i in facts["rdma"]}
    for port in config["interfaces"]:
        nic, rdma = interfaces.get(port["netdev"], {}), functions.get(port["rdma_device"], {})
        if (nic.get("mac", "").lower() != port["mac"] or nic.get("master")
                or nic.get("ipv4") != [port["address"]] or nic.get("mtu") != 9000
                or nic.get("operstate") != "UP" or rdma.get("netdev") != port["netdev"]
                or rdma.get("driver") != "mlx5_core"):
            raise ValueError("Approved data interface changed or is unavailable: " + port["netdev"])
        mapped = ipaddress.IPv6Address(rdma.get("gid") or "::").ipv4_mapped
        if mapped != ipaddress.ip_interface(port["address"]).ip or rdma.get("gid_index") != 3:
            # Extra IPv6 link-local addresses move the IPv4 GID past index 3; the hint names that cause.
            raise ValueError("GID3/RoCE link is unavailable: " + port["netdev"] + gid_index_hint(facts, port["netdev"]))
        if (rdma.get("gid_type") != "RoCE v2" or rdma.get("gid_netdev") != port["netdev"]
                or rdma.get("active_mtu") != 4096 or rdma.get("state") not in ("ACTIVE", "PORT_ACTIVE")):
            raise ValueError("GID3/RoCE link is unavailable: " + port["netdev"])
    return facts


def restore(config, *, collect=_collect_local, run=subprocess.run, root="/"):
    """Restore only missing routes/rules and relay table objects; refuse conflicting routes before mutation."""
    if config.get("ownership") == "observed":
        # An adopted fabric keeps its links, addresses and routes; only its relay table's missing objects return.
        if config.get("relays") is None:
            raise ValueError("This fabric belongs to its existing service; no restoration changes are authorized")
        rows = relay_table.restore(config["relays"], call=lambda argv: call(argv, run=run), root=root)
        return {"configured": True, "hardware_qualified": False,
                "relays": {"restored": sum(row["state"] == "restored" for row in rows),
                           "missing": relay_table.missing(rows)}}
    facts = observe(config, collect=collect)
    missing = []
    for desired in config["routes"]:
        entries = [r for r in facts["routes"] if r.get("dst") == desired["destination"]]
        if entries and (len(entries) != 1 or entries[0].get("dev") != desired["dev"] or entries[0].get("gateway") != desired["via"]):
            raise ValueError("Conflicting existing fabric route: " + desired["destination"])
        if not entries:
            missing.append(["ip", "route", "add", desired["destination"], "via", desired["via"], "dev", desired["dev"], "proto", "static"])
    for argv in missing:
        call(argv, run=run)
    for _, key, value in approved_settings(config):
        call(["sysctl", "-w", f"{key}={value}"], run=run)
    for incoming, outgoing in config["forwarding"]:
        rule = ["FORWARD", "-i", incoming, "-o", outgoing, "-m", "comment", "--comment", "sparkring:" + config["cluster_id"][:16], "-j", "ACCEPT"]
        exists = call(["iptables", "-w", "-C", *rule], run=run, accepted=(0, 1)).returncode == 0
        if not exists:
            call(["iptables", "-w", "-I", *rule], run=run)
    result = {"configured": True, "hardware_qualified": False}
    if config.get("relays") is not None:
        rows = relay_table.restore(config["relays"], call=lambda argv: call(argv, run=run), root=root)
        result["relays"] = {"restored": sum(row["state"] == "restored" for row in rows),
                            "missing": relay_table.missing(rows)}
    return result


def approved_settings(config):
    """``[(interface, key, value)]``: the per-interface IPv4 settings ``restore`` applies, in its order.

    ``key`` is the sysctl name, such as ``net.ipv4.conf.enp1s0f1np1.rp_filter``.
    Each fabric function named in the record's ``forwarding`` pairs gets
    FORWARDING_SETTINGS; a pair's record names none.
    """
    return [(interface, f"net.ipv4.conf.{interface}.{name}", value)
            for interface in sorted({i for pair in config["forwarding"] for i in pair})
            for name, value in FORWARDING_SETTINGS]


def route_text(route):
    """``198.18.4.0/24 via 198.18.6.1 dev enp1s0f1np1`` for an approved route of a fabric record."""
    return f"{route['destination']} via {route['via']} dev {route['dev']}"


def routed(row, route):
    """Whether an ``ip -j route`` row is the approved ``route``: same destination, gateway and device."""
    return (row.get("dst") == route["destination"] and row.get("gateway") == route["via"]
            and row.get("dev") == route["dev"])


def ipv4_addresses(rows):
    """``{netdev: ["198.18.6.2/24", ...]}`` from the rows of ``ip -j -4 address show``."""
    return {row.get("ifname"): [f"{a['local']}/{a['prefixlen']}" for a in row.get("addr_info") or []
                                if a.get("family") == "inet" and "local" in a and "prefixlen" in a]
            for row in rows}


def route_states(config, routes, addresses, *, root="/"):
    """``(route, state)`` for each approved route of the fabric record ``config``.

    ``routes`` are the rows of ``ip -j -4 route show table all``; ``addresses``
    maps each netdev to its IPv4 addresses (``ipv4_addresses``). ``state`` is:

    - ``present``: a route to the destination through the approved gateway and
      device exists;
    - ``conflict``: only other routes to the destination exist; SparkRing never
      replaces them;
    - ``no-link``: the device does not report carrier, because the Spark at the
      cable's other end is down or restarting the link, or the cable is out;
    - ``unconfigured``: the device has carrier but not yet its approved address
      and that address's subnet route, which NetworkManager adds when it
      activates the connection; the gateway is reachable only after that;
    - ``missing``: none of these; ``ip route add`` restores the route.
    """
    ports = {port["netdev"]: port for port in config["interfaces"]}
    result = []
    for route in config["routes"]:
        same = [row for row in routes if row.get("dst") == route["destination"]]
        address = ipaddress.ip_interface(ports[route["dev"]]["address"])
        if any(routed(row, route) for row in same):
            state = "present"
        elif same:
            state = "conflict"
        elif link_state(route["dev"], root=root)[0] is not True:
            state = "no-link"
        elif (str(address) not in addresses.get(route["dev"], ())
              or not any(row.get("dst") == str(address.network) and row.get("dev") == route["dev"]
                         and not row.get("gateway") for row in routes)):
            state = "unconfigured"
        else:
            state = "missing"
        result.append((route, state))
    return result


def _log(text):
    print("SparkRing node: " + text, file=sys.stderr, flush=True)


def add_routes(config, *, root="/", run=subprocess.run, log=_log):
    """Add the approved routes of ``config`` whose state (``route_states``) is ``missing``.

    Each is added with the command ``restore`` uses; no route is removed or
    replaced. Returns each approved route with its ``state``: ``restored``, or
    ``failed`` with the command's ``error``, where this call tried to add it,
    and otherwise its ``route_states`` state.
    """
    routes = json.loads(call(["ip", "-j", "-4", "route", "show", "table", "all"], run=run).stdout or "[]")
    addresses = ipv4_addresses(json.loads(call(["ip", "-j", "-4", "address", "show"], run=run).stdout or "[]"))
    rows = []
    for route, state in route_states(config, routes, addresses, root=root):
        row = dict(route, state=state)
        if state == "missing":
            try:
                call(["ip", "route", "add", route["destination"], "via", route["via"], "dev", route["dev"],
                      "proto", "static"], run=run)
            except (OSError, RuntimeError, subprocess.SubprocessError) as error:
                row.update(state="failed", error=str(error))
                log("could not restore approved fabric route " + route_text(route) + ": " + str(error))
            else:
                row["state"] = "restored"
                log("restored approved fabric route " + route_text(route))
        rows.append(row)
    return rows


def apply_settings(config, *, root="/", run=subprocess.run, log=_log):
    """Set the approved per-interface settings of ``config`` (``approved_settings``) that differ.

    A function whose netdev does not exist is skipped (``absent``). Each other
    setting is read with ``sysctl -n`` and, when it differs, written with the
    command ``restore`` uses; nothing else is read or written. Returns each
    setting as ``{"interface", "key", "value", "found", "state"}``, where
    ``state`` is ``present``, ``restored``, ``absent``, or ``failed`` with the
    command's ``error``.
    """
    rows = []
    for interface, key, value in approved_settings(config):
        row = {"interface": interface, "key": key, "value": value, "found": None}
        if not (Path(root) / "sys/class/net" / interface).exists():
            row["state"] = "absent"
            rows.append(row)
            continue
        try:
            row["found"] = call(["sysctl", "-n", key], run=run).stdout.strip()
            if row["found"] == value:
                row["state"] = "present"
            else:
                call(["sysctl", "-w", f"{key}={value}"], run=run)
                row["state"] = "restored"
                log(f"set approved fabric setting {key} to {value} (was {row['found']})")
        except (OSError, RuntimeError, subprocess.SubprocessError) as error:
            row.update(state="failed", error=str(error))
            log(f"could not set approved fabric setting {key} to {value}: {error}")
        rows.append(row)
    return rows


def restore_fabric(config, *, root="/", run=subprocess.run, log=_log):
    """Add the approved fabric routes of ``config`` that are missing and set its per-interface settings that differ.

    The host agent runs this every AGENT_INTERVAL seconds. sparkring-fabric.service
    applies both once per boot (``restore``); they are not part of any
    NetworkManager connection profile.

    - Routes (``add_routes``): a fabric function loses every route through it
      when it loses its IPv4 address. NetworkManager removes the address when
      the link loses carrier (the neighboring Spark reboots or restarts that
      ConnectX function, or the cable is out), and a driver restart of the
      function itself removes the netdev. NetworkManager adds the address
      again when the link returns; the routes are added once the link has
      carrier and that address.
    - Per-interface settings (``apply_settings``): a driver restart of a
      function recreates its netdev with the kernel's defaults
      (``net.ipv4.conf.default.*``, rp_filter 2 on Ubuntu). Carrier loss
      keeps them.
    - Forwarding rules are not restored here: iptables matches the interface
      by name, so the netdev's removal or carrier loss leaves the rules in place.

    It acts only while sparkring-fabric.service is active: that service's
    restoration in this boot succeeded and is not running at the moment.
    Stopping or disabling the service ends this restoration; a re-form
    disables it before it removes the routes. It changes only the record's
    routes and settings, never removes or replaces a route, and changes
    nothing once everything matches.

    - Relay table (``relays.restore``): a function's relay routes leave with
      its address, and a driver restart removes its ingress queue and
      filters; the record's objects are added again once the link is up.

    Returns None for a record without routes, forwarding and relays (a
    pair, or an adopted fabric); ``{"active": False, "routes": [],
    "settings": []}`` while the service is not active; else ``{"active":
    True, "routes": add_routes(...), "settings": apply_settings(...)}``,
    with ``relays`` (``relays.restore`` rows) for a record with a relay table.
    """
    validate(config)
    table = config.get("relays")
    observed = config.get("ownership") == "observed"
    if observed and not table or not (config["routes"] or config["forwarding"] or table):
        return None
    if call(["systemctl", "is-active", FABRIC_UNIT], run=run, accepted=(0, 3)).returncode:
        return {"active": False, "routes": [], "settings": []}
    # An adopted fabric (observed) has no routes or settings of its own; only its relay table returns.
    result = {"active": True, "routes": [] if observed else add_routes(config, root=root, run=run, log=log),
              "settings": [] if observed else apply_settings(config, root=root, run=run, log=log)}
    if table:
        try:
            result["relays"] = relay_table.restore(table, call=lambda argv: call(argv, run=run), root=root, log=log)
        except (OSError, ValueError, RuntimeError, subprocess.SubprocessError) as error:
            result["relays_error"] = str(error)
            log("could not check the relay table for restoration: " + str(error))
    return result


class LinkDown(ValueError):
    """Approved fabric functions report no carrier; ``next_action`` names the Sparks at the other ends."""

    def __init__(self, text, next_action):
        super().__init__(text)
        self.next_action = next_action


def neighbor(config, port):
    """The rank at the other end of an approved fabric function's cable.

    On rank r of a ring of n Sparks, port 0 (roles ``cw_*``) leads to rank
    (r + 1) mod n and port 1 (``ccw_*``) to rank (r - 1) mod n; in a pair,
    both lead to the other Spark.
    """
    return (config["rank"] + (1 if str(port.get("role", "")).startswith("cw_") else -1)) % config["size"]


def require_links(config, *, root="/"):
    """Raise LinkDown when an approved fabric function reports no carrier.

    The error names the functions by the rank their cable leads to, and the
    approved routes through them, which ``restore_fabric`` adds again when the
    link returns. A function whose carrier the kernel does not report, such as
    an administratively disabled one, is left to ``observe``.
    """
    down = {}
    for port in config["interfaces"]:
        if link_state(port["netdev"], root=root)[0] is False:
            down.setdefault(neighbor(config, port), []).append(port["netdev"])
    if not down:
        return
    ranks = sorted(down)
    links = " and ".join(f"to rank {rank} on {', '.join(down[rank])}" for rank in ranks)
    names = " and ".join(f"rank {rank}" for rank in ranks)
    text = (f"No link {links}: {names} {'is' if len(ranks) == 1 else 'are'} down or restarting the link, "
            "or the cable is out")
    netdevs = {netdev for rank in ranks for netdev in down[rank]}
    lost = [route["destination"] for route in config["routes"] if route["dev"] in netdevs]
    if lost:
        text += (f"; the fabric routes through {'them' if len(netdevs) > 1 else 'it'} ({', '.join(lost)}) "
                 "return with the link")
    raise LinkDown(text, f"start {names} or reconnect the cable")


def verify_persistence(config, facts, *, run=subprocess.run, restoration=None, active=True, root="/"):
    """Raise ValueError naming the first approved route, forwarding rule or per-interface setting that is missing.

    A missing route's error says why it is missing: another route to its
    destination is in its place; the agent's attempt to add it failed
    (``restoration``, the result of ``restore_fabric``); sparkring-fabric.service
    is not ``active``, so the agent does not add it; or else the agent adds it
    within AGENT_INTERVAL seconds. A per-interface setting (``approved_settings``)
    that differs is named with its value and the same reasons.
    """
    attempts = {row["destination"]: row for row in (restoration or {}).get("routes") or []}
    for expected in config["routes"]:
        same = [r for r in facts["routes"] if r.get("dst") == expected["destination"]]
        if any(routed(r, expected) for r in same):
            continue
        text = "Approved fabric route is missing: " + route_text(expected)
        error = (attempts.get(expected["destination"]) or {}).get("error")
        if same:
            text += f"; another route to {expected['destination']} is in its place, and SparkRing does not replace it"
        elif error:
            text += "; adding it failed: " + error
        elif not active:
            text += f"; sparkring-agent adds it only while {FABRIC_UNIT} is active"
        else:
            text += f"; sparkring-agent adds it again within {AGENT_INTERVAL} seconds"
        raise ValueError(text)
    for incoming, outgoing in config["forwarding"]:
        rule = ["FORWARD", "-i", incoming, "-o", outgoing, "-m", "comment", "--comment", "sparkring:" + config["cluster_id"][:16], "-j", "ACCEPT"]
        call(["iptables", "-w", "-C", *rule], run=run)
    tried = {row["key"]: row for row in (restoration or {}).get("settings") or []}
    for _, key, value in approved_settings(config):
        found = call(["sysctl", "-n", key], run=run).stdout.strip()
        if found == value:
            continue
        text = f"Approved fabric setting differs: {key} is {found}, approved {value}"
        error = (tried.get(key) or {}).get("error")
        if error:
            text += "; setting it failed: " + error
        elif not active:
            text += f"; sparkring-agent sets it only while {FABRIC_UNIT} is active"
        else:
            text += f"; sparkring-agent sets it again within {AGENT_INTERVAL} seconds"
        raise ValueError(text)
    table = config.get("relays")
    if table:
        rows = relay_table.observe(table, call=lambda argv: call(argv, run=run), root=root)
        if active and table.get("markers"):
            rows += relay_table.check_markers(table, root=root)
        absent = [row for row in relay_table.missing(rows) if row["state"] != "no-link"]
        if absent:
            row = absent[0]
            what = row.get("dst") or row.get("addr") or row.get("rdma") or f"{row.get('dev')} preference {row.get('pref')}"
            raise ValueError(f"Relay table {row['kind']} {what} is {row['state']}"
                             + ("" if len(absent) == 1 else f", and {len(absent) - 1} more objects")
                             + f"; sparkring-agent adds missing objects while {FABRIC_UNIT} is active, "
                               "and sudo sparkring fabric verify lists each")


def _refuse_mesh_beside_markers(config, *, run=subprocess.run):
    """Refuse a record with relay markers while a mesh service runs here: both would claim the same RDMA packets."""
    if not (config.get("relays") or {}).get("markers"):
        return
    listing = call(["systemctl", "list-units", "--type=service", "--state=active", "--no-legend", "--plain",
                    *MESH_UNIT_PATTERNS], run=run).stdout
    running = sorted({line.split()[0] for line in listing.splitlines() if line.split()})
    if running:
        raise ValueError("A four-Spark mesh service runs on this Spark (" + ", ".join(running) + "); its markers "
                         "and the relay table's would claim the same RDMA packets. Stop its model with sudo "
                         "sparkring down --execute on Node A, then run setup again")


def _comparable(config):
    return {key: value for key, value in config.items() if key not in REFRESHED_FIELDS}


def configure(config, *, root="/", collect=_collect_local, run=subprocess.run):
    """Save the approved fabric record and enable the units that restore it at every boot.

    A recorded configuration that differs is refused, except in the fields
    a setup of the same Sparks refreshes (``REFRESHED_FIELDS``: the layout
    name and the relay table). A record with relay markers enables and
    restarts ``sparkring-relay-marker.service``; one without disables it. A
    record with relay markers is refused while a mesh service runs here.
    """
    validate(config)
    if config["node_id"] != read(root, "/etc/sparkring/node.json")["node_id"]:
        raise ValueError("Configuration belongs to another node")
    path = location(root, "/etc/sparkring/fabric.json")
    if path.exists() and _comparable(read(root, "/etc/sparkring/fabric.json")) != _comparable(config):
        raise ValueError("Node already has another approved configuration; inspect before replacing it")
    _refuse_mesh_beside_markers(config, run=run)
    observe(config, collect=collect)
    save(root, "/etc/sparkring/fabric.json", config)
    call(["systemctl", "enable", "sparkring-fabric.service"], run=run)
    # A failed start stays visible; repeating the same configuration is idempotent.
    call(["systemctl", "restart", "sparkring-fabric.service"], run=run)
    markers = bool((config.get("relays") or {}).get("markers"))
    if markers:
        call(["systemctl", "enable", MARKER_UNIT], run=run)
        call(["systemctl", "restart", MARKER_UNIT], run=run)
    else:
        call(["systemctl", "disable", "--now", MARKER_UNIT], run=run, accepted=(0, 1, 5))
    return {"persisted": True, "cluster_id": config["cluster_id"], "relay_markers": markers}


def relay_markers(*, root="/", popen=subprocess.Popen):
    """``sparkring node relay-markers``: run this Spark's relay markers until stopped (sparkring-relay-marker.service)."""
    config = read(root, "/etc/sparkring/fabric.json")
    validate(config)
    table = config.get("relays")
    if not table or not table.get("markers"):
        _log("this Spark's fabric record has no relay markers")
        return 0
    return relay_table.supervise(table, popen=popen)


RETIRED = "/var/lib/sparkring/retired"
# The package's units that setup enables. A unit file of the same name in /etc/systemd/system takes precedence
# over the package's (/usr/lib/systemd/system), so setup would start another program under that name.
SETUP_UNITS = (FABRIC_UNIT, MARKER_UNIT, "sparkring-hairpin.service", "sparkring-agent.service")


def unit_overrides(*, root="/"):
    """The files in ``/etc/systemd/system`` that replace or change this package's ``SETUP_UNITS`` on this Spark:
    a unit file of the same name, or a drop-in (``<unit>.d/*.conf``). An enable link is neither."""
    found = []
    for unit in SETUP_UNITS:
        path = location(root, f"/etc/systemd/system/{unit}")
        if path.is_file() and not path.is_symlink():
            found.append(f"/etc/systemd/system/{unit}")
        drop_ins = location(root, f"/etc/systemd/system/{unit}.d")
        if drop_ins.is_dir():
            found += [f"/etc/systemd/system/{unit}.d/{item.name}" for item in sorted(drop_ins.iterdir())
                      if item.name.endswith(".conf")]
    return found


def retire_record(*, root="/", reason, now=None):
    """Move this Spark's fabric record (``/etc/sparkring/fabric.json``) aside with a receipt; return the directory.

    The record moves to ``/var/lib/sparkring/retired/<UTC time>-<reason>/etc/sparkring/fabric.json``, and the
    directory's ``receipt.json`` names it and the command that puts it back. No route, address, service or
    other file changes: a record's boot service reads it only while that service is enabled."""
    source = location(root, "/etc/sparkring/fabric.json")
    stamp = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime(now if now is not None else time.time()))
    name = f"{RETIRED}/{stamp}-{reason}"
    directory = location(root, name)
    target = directory / "etc/sparkring/fabric.json"
    target.parent.mkdir(parents=True, exist_ok=False, mode=0o700)
    os.replace(source, target)
    receipt = {"schema": "sparkring-retired-record/v1", "reason": reason,
               "moved": {"/etc/sparkring/fabric.json": f"{name}/etc/sparkring/fabric.json"},
               "restore": f"sudo mv {name}/etc/sparkring/fabric.json /etc/sparkring/fabric.json"}
    (directory / "receipt.json").write_text(json.dumps(receipt, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    return name


def adopt(config, *, root="/", collect=_collect_local, run=subprocess.run, retire=False):
    """Record an existing fabric as observed, and keep its relay table in place, without any network change.

    The record changes no link, address, NetworkManager connection or route, and restarts no driver
    (``ownership`` ``observed``, no ``routes`` or ``forwarding``). With a relay table (``relays``) adoption
    adds only the table's objects that are missing (``relays.restore``, which never removes or replaces one:
    a route, neighbour or filter preference that is present stays as it is) and enables
    ``sparkring-fabric.service``, which adds them again at every boot, and, with markers,
    ``sparkring-relay-marker.service``. A Spark that records another setup is refused unless ``retire``
    moves that record aside first (``retire_record``)."""
    validate(config)
    if config["node_id"] != read(root, "/etc/sparkring/node.json")["node_id"]:
        raise ValueError("Observed configuration belongs to another node")
    if config.get("ownership") != "observed" or config["routes"] or config["forwarding"]:
        raise ValueError("Adoption must not request network changes")
    _refuse_mesh_beside_markers(config, run=run)
    observe(config, collect=collect)
    path = location(root, "/etc/sparkring/fabric.json")
    result = {"adopted": True, "network_changed": False}
    if path.exists() and read(root, "/etc/sparkring/fabric.json") != config:
        if not retire:
            raise ValueError("Node records another setup; inspect before replacing it")
        result["retired"] = retire_record(root=root, reason="adopt")
    save(root, "/etc/sparkring/fabric.json", config)
    table = config.get("relays")
    if table:
        rows = relay_table.restore(table, call=lambda argv: call(argv, run=run), root=root)
        result["relays"] = {"restored": sum(row["state"] == "restored" for row in rows),
                            "present": sum(row["state"] == "present" for row in rows),
                            "missing": relay_table.missing(rows)}
        call(["systemctl", "enable", FABRIC_UNIT], run=run)
        call(["systemctl", "restart", FABRIC_UNIT], run=run)
        if table.get("markers"):
            call(["systemctl", "enable", MARKER_UNIT], run=run)
            call(["systemctl", "restart", MARKER_UNIT], run=run)
        result["relay_markers"] = bool(table.get("markers"))
    return result


def workspace(operator, name, *, root="/", account=None):
    """Create the cluster's workspace (``/srv/sparkring/<name>``) and the controller state directory for the SSH
    operator, or accept them when they exist and belong to that operator.

    The controller state directory (``/var/lib/sparkring/controller``) may also belong to root: a setup whose
    operator signed in as root left it so, and every command that uses it runs as root."""
    if account is None:
        import pwd
        account = pwd.getpwnam(operator)
    if not re.fullmatch(r"[a-z][a-z0-9-]{0,39}", name):
        raise ValueError("Choose a lowercase cluster name")
    # Source stagers claim empty per-model workspaces below this parent.
    path = location(root, "/srv/sparkring/" + name)
    controller = location(root, "/var/lib/sparkring/controller")
    for directory in (path, controller):
        if directory.exists():
            owners = (account.pw_uid, 0) if directory == controller else (account.pw_uid,)
            if directory.stat().st_uid not in owners:
                raise ValueError("State/workspace belongs to another operator: " + str(directory))
        else:
            directory.mkdir(parents=True, mode=0o700)
            os.chown(directory, account.pw_uid, account.pw_gid)
    return {"workspace": str(path), "controller": str(controller)}


def observation_identity(*, root="/"):
    """Read stable host and boot identities without creating or repairing state."""
    result = {"node_id": None, "boot_id": None, "identity_errors": {}}
    for field, name in (("node_id", "/etc/sparkring/node.json"), ("boot_id", "/proc/sys/kernel/random/boot_id")):
        try:
            raw = read(root, name)[field] if field == "node_id" else location(root, name).read_text().strip()
            result[field] = str(uuid.UUID(raw))
        except (OSError, ValueError, KeyError, TypeError, AttributeError) as error:
            result["identity_errors"][field] = type(error).__name__
    return result


def mesh_units_without_start_check(*, root="/", run=subprocess.run):
    """Return warnings for mesh unit files whose loaded definition lacks the hairpin start check.

    The package's systemd generator adds the check to every regular unit file
    matching MESH_UNIT_PATTERNS at each daemon-reload; a unit written after the
    last daemon-reload has no check until the next one.
    """
    directory = Path(root) / "etc/systemd/system"
    names = sorted({path.name for pattern in MESH_UNIT_PATTERNS for path in directory.glob(pattern)
                    if path.is_file() and not path.is_symlink()})
    warnings = []
    for name in names:
        try:
            paths = call(["systemctl", "show", "-p", "DropInPaths", "--value", name], run=run).stdout.split()
        except (OSError, RuntimeError, subprocess.SubprocessError) as error:
            warnings.append(f"mesh unit {name}: cannot read its drop-ins to confirm the hairpin start check: {error}")
            continue
        if not any(PurePosixPath(path).name == MESH_START_CHECK and PurePosixPath(path).parent.name == name + ".d"
                   for path in paths):
            warnings.append(f"mesh unit {name} has no hairpin start check; run sudo systemctl daemon-reload")
    return warnings


def hairpin_rows(config, facts):
    """Evaluate the in-effect rule for each fabric function of the record, from collected facts.

    Rows are hairpin_setting.evaluate results with the function's netdev and
    RDMA device added. A function whose devlink values, reload statistics or
    offload setting are missing from the facts is "unknown".
    """
    rdma = {row.get("device"): row for row in facts.get("rdma") or []}
    nics = {row.get("name"): row for row in facts.get("interfaces") or []}
    rows = []
    for port in config["interfaces"]:
        devlink = rdma.get(port["rdma_device"], {}).get("devlink") or {}
        parameters = devlink.get("parameters") or {}
        nic = nics.get(port["netdev"], {})
        row = hairpin_setting.evaluate(
            {name: (parameters.get(name) or {}).get("value") for name in hairpin_setting.PARAMETERS},
            devlink.get("reload"),
            hairpin_setting.offload_setting(nic.get("hw_tc_offload"), nic.get("hw_tc_offload_fixed")))
        rows.append({"netdev": port["netdev"], "rdma_device": port["rdma_device"], **row})
    return rows


def require_hairpin(rows):
    """Raise HairpinNotInEffect naming every function of hairpin_rows that is not in effect.

    Functions that share a shortfall are named together, for example
    ``enp1s0f0np0, enp1s0f1np1: hairpin_queue_size 1024, required 8192``.
    """
    failing = [row for row in rows if row["state"] != hairpin_setting.IN_EFFECT]
    if failing:
        raise HairpinNotInEffect("ConnectX hairpin setting not in effect on " + hairpin_setting.grouped(failing))


def check_hairpin(config, facts, warnings, *, root="/", run=subprocess.run):
    """Apply the in-effect rule to a relaying Spark's record; append M10 warnings, then raise if needed.

    The rule is evaluated from the collected facts. hairpin.status adds the
    warnings about arming and suspended boot runs; when it cannot be read,
    that is a warning and the rule still decides.
    """
    rows = hairpin_rows(config, facts)
    from runtime.host import hairpin
    try:
        warnings += hairpin.status(facts=facts, root=root, run=run).get("warnings") or []
    except (ValueError, KeyError, TypeError, AttributeError, OSError, RuntimeError,
            subprocess.SubprocessError) as error:
        warnings.append("ConnectX hairpin approval and boot state unavailable: " + str(error))
    require_hairpin(rows)


def link_state(netdev, *, root="/"):
    """``(carrier, operstate)`` of a network interface from sysfs.

    ``carrier`` is True or False, or None when the kernel does not report it
    (for example on an interface that is administratively down); ``operstate``
    is the kernel's text, such as ``up``, ``down`` or ``lowerlayerdown``, or None.
    """
    values = []
    for name in ("carrier", "operstate"):
        try:
            values.append((Path(root) / "sys/class/net" / netdev / name).read_text().strip())
        except OSError:
            values.append(None)
    return {"1": True, "0": False}.get(values[0]), values[1]


def link_text(carrier, operstate):
    """``no link``, ``link up`` or the kernel's operational state of an interface."""
    if carrier is False:
        return "no link"
    if carrier is True:
        return "link up"
    return f"state {operstate}" if operstate else "state unknown"


def control_report(*, root="/", run=subprocess.run, now=time.time):
    """This Spark's administration tunnel peers, or None without a recorded control network.

    Returns ``{"interface_up", "peers"}``. Each peer row names its recorded
    fabric link (``netdev``, with ``carrier`` and ``operstate`` from sysfs),
    the ``endpoint`` WireGuard uses and ``handshake_age_s``, the seconds since
    its latest handshake (None when there was none since the interface was
    created). ``path`` is the path that endpoint names: ``via`` (``cable`` or
    ``lan``), the local ``netdev``, the peer's ``address`` on it and whether
    it is the ``primary`` path, the recorded link; it is None when the
    endpoint names no known path. ``fallbacks`` counts the peer's fallback
    paths; a peer without any has no administration path while its recorded
    link is down. ``address``
    is the peer's own control address for a peer below this Spark in the
    administration tree; the peer above a worker may route every address, so
    its address is None and ``upstream`` is true.
    """
    if not location(root, "/etc/sparkring/control.json").exists():
        return None
    config = read(root, "/etc/sparkring/control.json")
    dump = call(["wg", "show", control.INTERFACE, "dump"], run=run, accepted=(0, 1))
    lines = dump.stdout.splitlines() if dump.returncode == 0 else []
    seen = {}
    for line in lines[1:]:
        fields = line.split("\t")
        if len(fields) >= 5:
            seen[fields[0]] = {"endpoint": None if fields[2] == "(none)" else fields[2],
                               "handshake": int(fields[4]) if fields[4].isdigit() else 0}
    peers = []
    for peer in config.get("peers") or []:
        allowed = peer.get("allowed_ips") or []
        # A worker's upstream peer routes Node A's address, which is never below the worker.
        upstream = bool(allowed) and (allowed == ["0.0.0.0/0"] or not config.get("head")
                                      and f"{config.get('head_address')}/32" in allowed)
        carrier, operstate = link_state(peer["netdev"], root=root)
        observed = seen.get(peer.get("key"), {})
        handshake = observed.get("handshake") or 0
        options = control.paths(config, peer)
        index = control.match(options, observed.get("endpoint"))
        path = None if index is None else {"via": options[index]["via"], "netdev": options[index]["netdev"],
                                           "address": options[index]["peer"], "primary": index == 0}
        peers.append({"id": peer.get("id"), "address": None if upstream or not allowed else allowed[0].split("/")[0],
                      "upstream": upstream, "netdev": peer["netdev"], "carrier": carrier, "operstate": operstate,
                      "endpoint": observed.get("endpoint"),
                      "handshake_age_s": max(0, int(now() - handshake)) if handshake else None,
                      "path": path, "fallbacks": len(options) - 1})
    return {"interface_up": bool(lines), "peers": peers}


def fallback_path(peer):
    """``LAN 192.0.2.12`` or ``cable enp1s0f0np0``: the fallback path a peer row of control_report uses; else None."""
    path = peer.get("path")
    if not path or path.get("primary"):
        return None
    return control.path_text({"via": path["via"], "netdev": path["netdev"], "peer": path["address"]})


def fallback_text(peer):
    """``over LAN 192.0.2.12 (primary cable enp1s0f1np1: no link)`` for a peer row on a fallback path; else None."""
    used = fallback_path(peer)
    if used is None:
        return None
    return f"over {used} (primary cable {peer['netdev']}: {link_text(peer.get('carrier'), peer.get('operstate'))})"


def age_text(seconds):
    """``never``, ``40 s ago``, ``46 min ago`` or ``3 h ago``."""
    if seconds is None:
        return "never"
    if seconds < 120:
        return f"{int(seconds)} s ago"
    if seconds < 7200:
        return f"{int(seconds // 60)} min ago"
    return f"{int(seconds // 3600)} h ago"


def tunnel_problems(report):
    """One line per administration tunnel peer that lacks a recent handshake or runs over a fallback path.

    A peer without a handshake in the last HANDSHAKE_STALE seconds gets a line
    naming the peer (its control address, or ``the Spark above this one`` for
    the peer above a worker), the latest handshake, the fallback path in use
    if any and the state of its recorded link. A peer that answers over a
    fallback path gets a line naming that path and its recorded link's state
    (``fallback_text``).
    """
    if not report:
        return []
    if not report.get("interface_up"):
        return [f"admin tunnel {control.INTERFACE} is not up"]
    lines = []
    for peer in report.get("peers") or []:
        age = peer.get("handshake_age_s")
        name = peer.get("address") or ("the Spark above this one" if peer.get("upstream") else peer.get("id"))
        fallback = fallback_text(peer)
        if age is not None and age <= HANDSHAKE_STALE:
            if fallback:
                lines.append(f"admin tunnel to {name} runs {fallback}")
            continue
        trying = f" over {fallback_path(peer)}" if fallback else ""
        lines.append(f"admin tunnel to {name} has no recent handshake (last {age_text(age)}){trying}; "
                     f"{peer['netdev']}: {link_text(peer.get('carrier'), peer.get('operstate'))}")
    return lines


def marker_processes(*, root="/"):
    """PIDs of the mesh supervisor's marker processes running on this Spark.

    A managed marker runs as ``BINARY --device DEV --source-port 65535 ...
    --attach --managed``; the supervisor starts two per rank. Its unit uses
    ``KillMode=process``, so markers keep forwarding when the supervisor
    process itself is lost, and only the mesh's own cleanup reaps them.
    """
    found = []
    try:
        entries = list((Path(root) / "proc").iterdir())
    except OSError:
        return found
    for entry in entries:
        if not entry.name.isdigit():
            continue
        try:
            argv = (entry / "cmdline").read_bytes().decode(errors="replace").rstrip("\0").split("\0")
        except OSError:
            continue
        if "--attach" in argv and "--managed" in argv and "--source-port" in argv:
            found.append(int(entry.name))
    return sorted(found)


def last_error(unit, *, run=subprocess.run):
    """The newest error line that ``unit``'s own processes logged in this boot, or None.

    The mesh supervisor reports its failure as a JSON ``mesh_failure`` event
    whose ``error`` is the cause, followed by JSON events of its cleanup. A
    start that fails before the supervisor runs, such as a start check that
    refuses it, ends with a plain text line. systemd's own messages about the
    unit are not the unit's processes and are not read.
    """
    output = call(["journalctl", "_SYSTEMD_UNIT=" + unit, "-b", "--no-pager", "-o", "cat", "-n", "200"],
                  run=run, accepted=(0, 1)).stdout
    text = error = None
    for line in reversed(output.splitlines()):
        line = line.strip()
        if not line:
            continue
        try:
            event = json.loads(line) if line.startswith("{") else None
        except ValueError:
            event = None
        if isinstance(event, dict):
            if event.get("event") == "mesh_failure" and event.get("error"):
                # A plain line newer than the failure belongs to a later start.
                return (text or str(event["error"]))[:ERROR_TEXT]
            error = error or (str(event["error"]) if event.get("error") else None)
        else:
            text = text or line
    value = text or error
    return value[:ERROR_TEXT] if value else None


def mesh_report(*, root="/", run=subprocess.run):
    """The SparkRing mesh units of this four-Spark ring member and its marker processes.

    Returns ``{"active", "failed", "markers"}``: the names of active mesh
    units; each failed unit with systemd's ``result`` (``exit-code`` after the
    supervisor's own orderly stop or a failed start; ``watchdog``, ``signal``
    or ``core-dump`` when the supervisor process was lost) and ``error``, its
    last logged error line (``last_error``); and the PIDs of running marker
    processes. Markers while no mesh unit is active were left by a supervisor
    that ended without stopping them.
    """
    listing = call(["systemctl", "list-units", "--type=service", "--all", "--no-legend", "--plain",
                    *MESH_UNIT_PATTERNS], run=run).stdout
    active, failed = [], []
    for line in listing.splitlines():
        fields = line.split()
        if fields and fields[0] in ("●", "*", "x"):
            fields = fields[1:]
        if len(fields) < 3:
            continue
        unit, state = fields[0], fields[2]
        if state == "active":
            active.append(unit)
        elif state == "failed":
            result = call(["systemctl", "show", "-p", "Result", "--value", unit], run=run).stdout.strip()
            failed.append({"unit": unit, "result": result or None, "error": last_error(unit, run=run)})
    return {"active": active, "failed": failed, "markers": marker_processes(root=root)}


def mesh_failure_text(row):
    """``UNIT failed: ERROR`` for one failed unit of ``mesh_report``."""
    return f"{row['unit']} failed: " + (row.get("error") or f"systemd result {row.get('result') or 'unknown'}")


def orphaned_markers(report):
    """Whether marker processes run on a Spark of ``mesh_report`` while none of its mesh units is active."""
    return bool(report) and bool(report.get("markers")) and not report.get("active")


def parked_mesh(reference, parked, active=()):
    """Whether the mesh of site ``reference`` is among the ``parked`` units (``native_mesh.parked_units``) and not ``active``.

    A deployment created by an earlier SparkRing source starts a parked mesh
    without removing its record, so a running unit never counts as parked.
    """
    if not parked:
        return False
    from runtime.host import native_mesh
    try:
        unit = native_mesh.mesh_unit(reference["site_path"])
    except (ValueError, KeyError, TypeError, AttributeError):
        return False
    return unit in parked and unit not in active


def snapshot(*, root="/", collect=_collect_local, run=subprocess.run, now=time.time, repair=False):
    """The ``sparkring-node-status/v1`` document of this Spark, as the agent records it every 30 seconds.

    With ``repair``, which only the agent passes, the approved fabric routes
    that are missing while their link is up are added, and the approved
    per-interface settings that differ are set, first (``restore_fabric``), so
    what this restores counts as present. An approved fabric function without
    carrier makes the Spark ``needs-attention`` with an error naming the rank
    at the other end of its cable (``require_links``), ahead of a failed mesh
    unit, which that lost link causes.

    A Spark with a recorded administration network adds ``control``
    (``control_report``) and a warning per tunnel peer without a recent
    handshake. A four-Spark cycle member adds ``mesh`` (``mesh_report``); when
    the fabric check fails while a mesh unit has failed, the error names that
    unit and its last log line, and the ring check's finding becomes a warning.
    A Spark that relays between its cables (``relays_hairpin``) must have the
    ConnectX hairpin setting in effect, and a record with a relay table must
    have its routes, neighbors, filters and markers in place.

    On a Spark that relays, a ConnectX function whose restart failed in this
    boot and that carries the administration tunnel to other Sparks cuts
    their path to Node A; ``sudo sparkring hairpin`` cannot reach them, so the
    next action is then to reboot this Spark, whose next boot restarts no
    function (``hairpin.reboot_advice``).
    """
    result = {"schema": "sparkring-node-status/v1", "observed_at": now(), "hostname": socket.gethostname(),
              **observation_identity(root=root), "source": "host-agent",
              "hardware_qualified": False, "state": "not-configured", "next_action": "sparkring setup"}
    if not location(root, "/etc/sparkring/fabric.json").exists():
        return result
    warnings = []
    advice = None
    reads = (ValueError, KeyError, TypeError, OSError, RuntimeError, subprocess.SubprocessError)
    # Read on its own, so a failing fabric check still reports the tunnel.
    try:
        tunnel = control_report(root=root, run=run, now=now)
    except reads as error:
        tunnel = {"error": str(error)}
    if tunnel is not None:
        result["control"] = tunnel
        warnings += tunnel_problems(tunnel) if "error" not in tunnel else [
            "admin tunnel state unavailable: " + tunnel["error"]]
    try:
        config = read(root, "/etc/sparkring/fabric.json")
        result.update(rank=config["rank"], size=config["size"], cluster_id=config["cluster_id"])
        relaying = relays_hairpin(config)
        if relaying:
            from runtime.host import hairpin
            advice = hairpin.reboot_advice(root=root)
        if mesh_ring(config):
            # Read before the fabric check, which a failed mesh can fail.
            try:
                result["mesh"] = mesh_report(root=root, run=run)
            except reads as error:
                result["mesh"] = {"error": str(error)}
            if orphaned_markers(result["mesh"]):
                warnings.append("mesh marker processes run while no mesh unit is active; the mesh's own cleanup "
                                "must stop them before the mesh starts again")
            warnings += mesh_units_without_start_check(root=root, run=run)
            # native_mesh imports this module.
            from runtime.host import native_mesh
            warnings += native_mesh.code_warnings(root=root)
        if not relaying and location(root, "/etc/sparkring/hairpin.json").exists():
            warnings.append("hairpin approval on a Spark that does not relay between its cables: "
                            "sudo sparkring node hairpin revoke")
        validate(config)
        restoration = None
        if repair:
            try:
                restoration = restore_fabric(config, root=root, run=run)
            except reads as error:
                warnings.append("approved fabric routes and settings could not be checked for restoration: "
                                + str(error))
        require_links(config, root=root)
        facts = observe(config, collect=collect)
        if relaying:
            # Checked before the fabric routes, the fabric service and the mesh:
            # a mesh that its start check refused then reports the root cause.
            check_hairpin(config, facts, warnings, root=root, run=run)
        active = config.get("ownership") == "observed" or not call(
            ["systemctl", "is-active", FABRIC_UNIT], run=run, accepted=(0, 3)).returncode
        verify_persistence(config, facts, run=run, restoration=restoration, active=active, root=root)
        if config.get("ownership") == "observed" and config.get("native_mesh"):
            from runtime.common import qwen_mesh
            from runtime.host import native_mesh
            mesh = config["native_mesh"]
            # A mesh parked while two-Spark models serve on the ring's halves is not checked.
            if not parked_mesh(mesh.get("reference"), native_mesh.parked_units(root=root),
                               (result.get("mesh") or {}).get("active") or ()):
                qwen_mesh.check(mesh["reference"], config["rank"], mesh["hcas"], 3, mesh["host_ip"])
        elif not active:
            raise ValueError("Fabric service is not active; inspect journalctl -u sparkring-fabric")
        result.update(state="network-configured", next_action="sparkring models",
                      containers=[{"name": c.get("name"), "state": c.get("state")} for c in (facts["docker"].get("containers") or [])],
                      model_ready=None)
        if config.get("ownership") == "observed":
            result["state"] = "existing-network-verified"
    except (ValueError, KeyError, OSError, RuntimeError, subprocess.SubprocessError) as error:
        text, action = str(error), advice or getattr(error, "next_action", None)
        failed = (result.get("mesh") or {}).get("failed") or []
        if failed and action is None:
            # A failed mesh unit is the cause of the ring check's missing
            # objects; its own log line says why it failed.
            warnings.append(text)
            text, action = mesh_failure_text(failed[0]), "journalctl -u " + failed[0]["unit"] + " -b"
        result.update(state="needs-attention", error=text, next_action=action or "sparkring status --refresh")
    if warnings:
        result["warnings"] = warnings
    return result


def status(*, root="/", now=time.time):
    try:
        result = read(root, "/run/sparkring/status.json")
    except FileNotFoundError:
        return {"state": "agent-unavailable", "next_action": "systemctl status sparkring-agent", "hardware_qualified": False}
    age = now() - result["observed_at"]
    result["age_seconds"] = round(age, 1)
    if age < -5 or age > 90:
        result.update(state="stale", next_action="systemctl status sparkring-agent")
    return result


def agent(*, root="/", once=False):
    """Record this Spark's status every AGENT_INTERVAL seconds, restoring approved fabric routes and settings first.

    Package installation restarts sparkring-agent.service, so an updated
    package restores missing routes and differing settings without setup or a
    reboot.
    """
    while True:
        save(root, "/run/sparkring/status.json", snapshot(root=root, repair=True))
        if once:
            return
        time.sleep(AGENT_INTERVAL)
