"""Local node identity, approved boot configuration, and read-only observations.

Only the node CLI runs privileged operations. No listening control socket or
sudoers rule is installed; setup uses the operator's existing SSH/sudo authority.
"""
import ipaddress
import json
import os
from pathlib import Path, PurePosixPath
import re
import socket
import subprocess
import time
import uuid

from runtime.common import distribution
from runtime.host import control
from runtime.host.discovery import target
from scripts import hairpin_setting
from scripts.deploy_inventory import _collect_local, _request, validate_inventory

ROOT = Path(__file__).resolve().parents[2]
# Generated by packaging/debian/sparkring-hairpin-mesh-check for every mesh unit file.
MESH_START_CHECK = "10-sparkring-hairpin.conf"
MESH_UNIT_PATTERNS = ("sparkring-mesh.service", "sparkring-*-mesh.service")
HAIRPIN_REMEDY = "on Node A: sudo sparkring hairpin"
# Seconds after which WireGuard discards a session that no handshake renewed
# (its REJECT_AFTER_TIME). With PersistentKeepalive a reachable peer renews the
# session about every two minutes, so an older handshake means no path.
HANDSHAKE_STALE = 180
# The characters of an error line that a status document carries.
ERROR_TEXT = 300


class HairpinNotInEffect(ValueError):
    """A fabric function of a four-Spark ring lacks the ConnectX hairpin setting."""

    next_action = HAIRPIN_REMEDY


def location(root, name):
    path = Path(root) / str(name).lstrip("/")
    if any(p.is_symlink() for p in (path, *path.parents)):
        raise ValueError("Node state path contains a symlink: " + str(path))
    return path


def read(root, name):
    return json.loads(location(root, name).read_text(encoding="utf-8"))


def save(root, name, value, mode=0o644):
    path = location(root, name)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".writing")
    location(root, temporary.relative_to(Path(root)))
    with temporary.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(json.dumps(value, indent=2) + "\n")
    temporary.chmod(mode)
    temporary.replace(path)


def call(argv, *, run=subprocess.run, accepted=(0,)):
    result = run(argv, capture_output=True, text=True, timeout=90)
    if result.returncode not in accepted:
        raise RuntimeError(" ".join(argv[:4]) + ": " + result.stderr.strip())
    return result


def initialize(root="/"):
    path = location(root, "/etc/sparkring/node.json")
    if path.exists():
        document = read(root, "/etc/sparkring/node.json")
        uuid.UUID(document["node_id"])
    else:
        document = {"schema": "sparkring-node/v1", "node_id": str(uuid.uuid4())}
        save(root, "/etc/sparkring/node.json", document)
    # Avahi advertises candidates; SSH host keys establish their identity.
    service = location(root, "/etc/avahi/services/sparkring.service")
    service.parent.mkdir(parents=True, exist_ok=True)
    service.write_text('''<?xml version="1.0" standalone="no"?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group><name replace-wildcards="yes">SparkRing on %h</name>
<service><type>_sparkring._tcp</type><port>22</port>
<txt-record>protocol=ssh</txt-record></service></service-group>
''', encoding="utf-8")
    return document


def inspect(rank, ssh_target, management, witness, *, root="/", collect=_collect_local, run=subprocess.run):
    target(ssh_target)
    if management != ssh_target.split("@", 1)[1] or management == witness:
        raise ValueError("Use the host management IP and another Spark as its route witness")
    facts = collect(_request(rank, ssh_target, management, (), witness))
    validate_inventory(facts, require_ready=True)
    lldp = json.loads(call(["lldpctl", "-f", "json"], run=run).stdout)
    identity = read(root, "/etc/sparkring/node.json")
    record = distribution.installed(ROOT)
    # hairpin imports this module; the function states come from the collected
    # facts, so the status adds no devlink call.
    from runtime.host import hairpin
    return {"schema": "sparkring-node-inventory/v1", "node_id": identity["node_id"],
            "hostname": socket.gethostname(), "revision": record["revision"] if record else None,
            "facts": facts, "lldp": lldp, "hairpin": hairpin.status(facts=facts, root=root, run=run)}


def validate(config):
    if config.get("schema") != "sparkring-fabric-state/v1" or not re.fullmatch("[0-9a-f]{64}", config.get("cluster_id", "")):
        raise ValueError("Invalid approved fabric state")
    uuid.UUID(config["node_id"])
    if config["size"] not in (2, 4) or type(config["rank"]) is not int or config["rank"] not in range(config["size"]):
        raise ValueError("Invalid rank or size")
    target(config["ssh_target"])
    management = config["management"]
    for key in ("address", "witness"):
        address = ipaddress.IPv4Address(management[key])
        if address.is_multicast or address.is_unspecified or address.is_loopback:
            raise ValueError("Invalid management address")
    if management["address"] == management["witness"]:
        raise ValueError("Management witness must be another host")
    ports = config["interfaces"]
    count = 2 if config["size"] == 2 else 4
    if len(ports) != count or len({p["netdev"] for p in ports}) != count:
        raise ValueError("Invalid fabric interfaces")
    nets = {}
    for p in ports:
        if not re.fullmatch(r"[A-Za-z0-9_-]{1,15}", p["netdev"]) or p["netdev"] == management["interface"]:
            raise ValueError("Invalid data interface or management interface selected")
        if not re.fullmatch(r"(?:[0-9a-f]{2}:){5}[0-9a-f]{2}", p["mac"]):
            raise ValueError("Expected data interface MAC")
        endpoint = ipaddress.IPv4Interface(p["address"])
        if endpoint.network.prefixlen != 24 or any(ipaddress.ip_address(management[k]) in endpoint.network for k in ("address", "witness")):
            raise ValueError("Fabric must use /24 subnets separate from management")
        nets[p["netdev"]] = endpoint.network
    if len(set(nets.values())) != count:
        raise ValueError("Fabric functions require separate subnets")
    for route in config["routes"]:
        network = ipaddress.IPv4Network(route["destination"])
        if (network.prefixlen != 24 or route["dev"] not in nets
                or ipaddress.IPv4Address(route["via"]) not in nets[route["dev"]]
                or any(ipaddress.ip_address(management[k]) in network for k in ("address", "witness"))
                or any(network.overlaps(n) for n in nets.values())):
            raise ValueError("Route must reach a remote fabric /24 through a verified data interface")
    if any(len(pair) != 2 or pair[0] == pair[1] or not set(pair) <= nets.keys() for pair in config["forwarding"]):
        raise ValueError("Forwarding must stay between distinct data interfaces")
    if config["size"] == 2 and (config["routes"] or config["forwarding"]):
        raise ValueError("Pair requires no routed fabric")
    return config


def observe(config, *, collect=_collect_local):
    validate(config)
    m = config["management"]
    facts = collect(_request(config["rank"], config["ssh_target"], m["address"], (), m["witness"]))
    management = facts["management"]
    if (management.get("error") or management.get("interface") != m["interface"]
            or (management.get("route_to_controller") or {}).get("dev") != m["interface"]):
        raise ValueError("Independent management path changed")
    interfaces = {i["name"]: i for i in facts["interfaces"]}
    functions = {i["device"]: i for i in facts["rdma"]}
    for port in config["interfaces"]:
        nic, rdma = interfaces.get(port["netdev"], {}), functions.get(port["rdma_device"], {})
        if (nic.get("mac", "").lower() != port["mac"] or nic.get("master")
                or nic.get("ipv4") != [port["address"]] or nic.get("mtu") != 9000
                or nic.get("operstate") != "UP" or rdma.get("netdev") != port["netdev"]
                or rdma.get("driver") != "mlx5_core"):
            raise ValueError("Approved data interface changed or is unavailable: " + port["netdev"])
        mapped = ipaddress.IPv6Address(rdma.get("gid") or "::").ipv4_mapped
        if (mapped != ipaddress.ip_interface(port["address"]).ip or rdma.get("gid_index") != 3
                or rdma.get("gid_type") != "RoCE v2" or rdma.get("gid_netdev") != port["netdev"]
                or rdma.get("active_mtu") != 4096 or rdma.get("state") not in ("ACTIVE", "PORT_ACTIVE")):
            raise ValueError("GID3/RoCE link is unavailable: " + port["netdev"])
    return facts


def restore(config, *, collect=_collect_local, run=subprocess.run):
    """Restore only missing routes/rules; refuse conflicting routes before mutation."""
    if config.get("ownership") == "observed":
        raise ValueError("This fabric belongs to its existing service; no restoration changes are authorized")
    facts = observe(config, collect=collect)
    missing = []
    for desired in config["routes"]:
        entries = [r for r in facts["routes"] if r.get("dst") == desired["destination"]]
        if entries and (len(entries) != 1 or entries[0].get("dev") != desired["dev"] or entries[0].get("gateway") != desired["via"]):
            raise ValueError("Conflicting existing fabric route: " + desired["destination"])
        if not entries:
            missing.append(["ip", "route", "add", desired["destination"], "via", desired["via"], "dev", desired["dev"], "proto", "static"])
    for argv in missing:
        call(argv, run=run)
    for interface in sorted({i for pair in config["forwarding"] for i in pair}):
        # Per-interface forwarding avoids enabling routing on management NICs.
        call(["sysctl", "-w", f"net.ipv4.conf.{interface}.forwarding=1"], run=run)
        call(["sysctl", "-w", f"net.ipv4.conf.{interface}.rp_filter=0"], run=run)
    for incoming, outgoing in config["forwarding"]:
        rule = ["FORWARD", "-i", incoming, "-o", outgoing, "-m", "comment", "--comment", "sparkring:" + config["cluster_id"][:16], "-j", "ACCEPT"]
        exists = call(["iptables", "-w", "-C", *rule], run=run, accepted=(0, 1)).returncode == 0
        if not exists:
            call(["iptables", "-w", "-I", *rule], run=run)
    return {"configured": True, "hardware_qualified": False}


def verify_persistence(config, facts, *, run=subprocess.run):
    for expected in config["routes"]:
        if not any(r.get("dst") == expected["destination"] and r.get("dev") == expected["dev"]
                   and r.get("gateway") == expected["via"] for r in facts["routes"]):
            raise ValueError("Approved fabric route is missing: " + expected["destination"])
    for incoming, outgoing in config["forwarding"]:
        rule = ["FORWARD", "-i", incoming, "-o", outgoing, "-m", "comment", "--comment", "sparkring:" + config["cluster_id"][:16], "-j", "ACCEPT"]
        call(["iptables", "-w", "-C", *rule], run=run)
    for interface in {i for pair in config["forwarding"] for i in pair}:
        if call(["sysctl", "-n", f"net.ipv4.conf.{interface}.forwarding"], run=run).stdout.strip() != "1":
            raise ValueError("Fabric forwarding is disabled: " + interface)


def configure(config, *, root="/", collect=_collect_local, run=subprocess.run):
    validate(config)
    if config["node_id"] != read(root, "/etc/sparkring/node.json")["node_id"]:
        raise ValueError("Configuration belongs to another node")
    path = location(root, "/etc/sparkring/fabric.json")
    if path.exists() and read(root, "/etc/sparkring/fabric.json") != config:
        raise ValueError("Node already has another approved configuration; inspect before replacing it")
    observe(config, collect=collect)
    save(root, "/etc/sparkring/fabric.json", config)
    call(["systemctl", "enable", "sparkring-fabric.service"], run=run)
    # A failed start stays visible; repeating the same configuration is idempotent.
    call(["systemctl", "restart", "sparkring-fabric.service"], run=run)
    return {"persisted": True, "cluster_id": config["cluster_id"]}


def adopt(config, *, root="/", collect=_collect_local):
    validate(config)
    if config["node_id"] != read(root, "/etc/sparkring/node.json")["node_id"]:
        raise ValueError("Observed configuration belongs to another node")
    if config.get("ownership") != "observed" or config["routes"] or config["forwarding"]:
        raise ValueError("Adoption must not request network changes")
    observe(config, collect=collect)
    path = location(root, "/etc/sparkring/fabric.json")
    if path.exists() and read(root, "/etc/sparkring/fabric.json") != config:
        raise ValueError("Node records another setup; inspect before replacing it")
    save(root, "/etc/sparkring/fabric.json", config)
    return {"adopted": True, "network_changed": False}


def workspace(operator, name, *, root="/"):
    import pwd
    account = pwd.getpwnam(operator)
    if not re.fullmatch(r"[a-z][a-z0-9-]{0,39}", name):
        raise ValueError("Choose a lowercase cluster name")
    # Source stagers claim empty per-model workspaces below this parent.
    path = location(root, "/srv/sparkring/" + name)
    controller = location(root, "/var/lib/sparkring/controller")
    for directory in (path, controller):
        if directory.exists():
            if directory.stat().st_uid != account.pw_uid:
                raise ValueError("State/workspace belongs to another operator: " + str(directory))
        else:
            directory.mkdir(parents=True, mode=0o700)
            os.chown(directory, account.pw_uid, account.pw_gid)
    return {"workspace": str(path), "controller": str(controller)}


def observation_identity(*, root="/"):
    """Read stable host and boot identities without creating or repairing state."""
    result = {"node_id": None, "boot_id": None, "identity_errors": {}}
    for field, name in (("node_id", "/etc/sparkring/node.json"), ("boot_id", "/proc/sys/kernel/random/boot_id")):
        try:
            raw = read(root, name)[field] if field == "node_id" else location(root, name).read_text().strip()
            result[field] = str(uuid.UUID(raw))
        except (OSError, ValueError, KeyError, TypeError, AttributeError) as error:
            result["identity_errors"][field] = type(error).__name__
    return result


def mesh_units_without_start_check(*, root="/", run=subprocess.run):
    """Return warnings for mesh unit files whose loaded definition lacks the hairpin start check.

    The package's systemd generator adds the check to every regular unit file
    matching MESH_UNIT_PATTERNS at each daemon-reload; a unit written after the
    last daemon-reload has no check until the next one.
    """
    directory = Path(root) / "etc/systemd/system"
    names = sorted({path.name for pattern in MESH_UNIT_PATTERNS for path in directory.glob(pattern)
                    if path.is_file() and not path.is_symlink()})
    warnings = []
    for name in names:
        try:
            paths = call(["systemctl", "show", "-p", "DropInPaths", "--value", name], run=run).stdout.split()
        except (OSError, RuntimeError, subprocess.SubprocessError) as error:
            warnings.append(f"mesh unit {name}: cannot read its drop-ins to confirm the hairpin start check: {error}")
            continue
        if not any(PurePosixPath(path).name == MESH_START_CHECK and PurePosixPath(path).parent.name == name + ".d"
                   for path in paths):
            warnings.append(f"mesh unit {name} has no hairpin start check; run sudo systemctl daemon-reload")
    return warnings


def hairpin_rows(config, facts):
    """Evaluate the in-effect rule for each fabric function of the record, from collected facts.

    Rows are hairpin_setting.evaluate results with the function's netdev and
    RDMA device added. A function whose devlink values, reload statistics or
    offload setting are missing from the facts is "unknown".
    """
    rdma = {row.get("device"): row for row in facts.get("rdma") or []}
    nics = {row.get("name"): row for row in facts.get("interfaces") or []}
    rows = []
    for port in config["interfaces"]:
        devlink = rdma.get(port["rdma_device"], {}).get("devlink") or {}
        parameters = devlink.get("parameters") or {}
        nic = nics.get(port["netdev"], {})
        row = hairpin_setting.evaluate(
            {name: (parameters.get(name) or {}).get("value") for name in hairpin_setting.PARAMETERS},
            devlink.get("reload"),
            hairpin_setting.offload_setting(nic.get("hw_tc_offload"), nic.get("hw_tc_offload_fixed")))
        rows.append({"netdev": port["netdev"], "rdma_device": port["rdma_device"], **row})
    return rows


def require_hairpin(rows):
    """Raise HairpinNotInEffect naming every function of hairpin_rows that is not in effect.

    Functions that share a shortfall are named together, for example
    ``enp1s0f0np0, enp1s0f1np1: hairpin_queue_size 1024, required 8192``.
    """
    failing = [row for row in rows if row["state"] != hairpin_setting.IN_EFFECT]
    if failing:
        raise HairpinNotInEffect("ConnectX hairpin setting not in effect on " + hairpin_setting.grouped(failing))


def check_hairpin(config, facts, warnings, *, root="/", run=subprocess.run):
    """Apply the in-effect rule to a four-Spark record; append M10 warnings, then raise if needed.

    The rule is evaluated from the collected facts. hairpin.status adds the
    warnings about arming and suspended boot runs; when it cannot be read,
    that is a warning and the rule still decides.
    """
    rows = hairpin_rows(config, facts)
    from runtime.host import hairpin
    try:
        warnings += hairpin.status(facts=facts, root=root, run=run).get("warnings") or []
    except (ValueError, KeyError, TypeError, AttributeError, OSError, RuntimeError,
            subprocess.SubprocessError) as error:
        warnings.append("ConnectX hairpin approval and boot state unavailable: " + str(error))
    require_hairpin(rows)


def link_state(netdev, *, root="/"):
    """``(carrier, operstate)`` of a network interface from sysfs.

    ``carrier`` is True or False, or None when the kernel does not report it
    (for example on an interface that is administratively down); ``operstate``
    is the kernel's text, such as ``up``, ``down`` or ``lowerlayerdown``, or None.
    """
    values = []
    for name in ("carrier", "operstate"):
        try:
            values.append((Path(root) / "sys/class/net" / netdev / name).read_text().strip())
        except OSError:
            values.append(None)
    return {"1": True, "0": False}.get(values[0]), values[1]


def link_text(carrier, operstate):
    """``no link``, ``link up`` or the kernel's operational state of an interface."""
    if carrier is False:
        return "no link"
    if carrier is True:
        return "link up"
    return f"state {operstate}" if operstate else "state unknown"


def control_report(*, root="/", run=subprocess.run, now=time.time):
    """This Spark's administration tunnel peers, or None without a recorded control network.

    Returns ``{"interface_up", "peers"}``. Each peer row names the fabric link
    that carries it (``netdev``, with ``carrier`` and ``operstate`` from
    sysfs), the ``endpoint`` WireGuard uses and ``handshake_age_s``, the
    seconds since its latest handshake (None when there was none since the
    interface was created). ``address`` is the peer's own control address for
    a peer below this Spark in the administration tree; the peer above a
    worker may route every address, so its address is None and ``upstream``
    is true. Each peer has exactly one recorded link, so a peer whose link
    lost its carrier has no administration path until the link returns.
    """
    if not location(root, "/etc/sparkring/control.json").exists():
        return None
    config = read(root, "/etc/sparkring/control.json")
    dump = call(["wg", "show", control.INTERFACE, "dump"], run=run, accepted=(0, 1))
    lines = dump.stdout.splitlines() if dump.returncode == 0 else []
    seen = {}
    for line in lines[1:]:
        fields = line.split("\t")
        if len(fields) >= 5:
            seen[fields[0]] = {"endpoint": None if fields[2] == "(none)" else fields[2],
                               "handshake": int(fields[4]) if fields[4].isdigit() else 0}
    peers = []
    for peer in config.get("peers") or []:
        allowed = peer.get("allowed_ips") or []
        # A worker's upstream peer routes Node A's address, which is never below the worker.
        upstream = bool(allowed) and (allowed == ["0.0.0.0/0"] or not config.get("head")
                                      and f"{config.get('head_address')}/32" in allowed)
        carrier, operstate = link_state(peer["netdev"], root=root)
        observed = seen.get(peer.get("key"), {})
        handshake = observed.get("handshake") or 0
        peers.append({"id": peer.get("id"), "address": None if upstream or not allowed else allowed[0].split("/")[0],
                      "upstream": upstream, "netdev": peer["netdev"], "carrier": carrier, "operstate": operstate,
                      "endpoint": observed.get("endpoint"),
                      "handshake_age_s": max(0, int(now() - handshake)) if handshake else None})
    return {"interface_up": bool(lines), "peers": peers}


def age_text(seconds):
    """``never``, ``40 s ago``, ``46 min ago`` or ``3 h ago``."""
    if seconds is None:
        return "never"
    if seconds < 120:
        return f"{int(seconds)} s ago"
    if seconds < 7200:
        return f"{int(seconds // 60)} min ago"
    return f"{int(seconds // 3600)} h ago"


def tunnel_problems(report):
    """One line per administration tunnel peer without a handshake in the last HANDSHAKE_STALE seconds.

    Each line names the peer (its control address, or ``Node A side`` for the
    peer above a worker), the latest handshake and the state of the link
    that carries it.
    """
    if not report:
        return []
    if not report.get("interface_up"):
        return [f"admin tunnel {control.INTERFACE} is not up"]
    lines = []
    for peer in report.get("peers") or []:
        age = peer.get("handshake_age_s")
        if age is not None and age <= HANDSHAKE_STALE:
            continue
        name = peer.get("address") or ("the Spark above this one" if peer.get("upstream") else peer.get("id"))
        lines.append(f"admin tunnel to {name} has no recent handshake (last {age_text(age)}); "
                     f"{peer['netdev']}: {link_text(peer.get('carrier'), peer.get('operstate'))}")
    return lines


def marker_processes(*, root="/"):
    """PIDs of the mesh supervisor's marker processes running on this Spark.

    A managed marker runs as ``BINARY --device DEV --source-port 65535 ...
    --attach --managed``; the supervisor starts two per rank. Its unit uses
    ``KillMode=process``, so markers keep forwarding when the supervisor
    process itself is lost, and only the mesh's own cleanup reaps them.
    """
    found = []
    try:
        entries = list((Path(root) / "proc").iterdir())
    except OSError:
        return found
    for entry in entries:
        if not entry.name.isdigit():
            continue
        try:
            argv = (entry / "cmdline").read_bytes().decode(errors="replace").rstrip("\0").split("\0")
        except OSError:
            continue
        if "--attach" in argv and "--managed" in argv and "--source-port" in argv:
            found.append(int(entry.name))
    return sorted(found)


def last_error(unit, *, run=subprocess.run):
    """The newest error line that ``unit``'s own processes logged in this boot, or None.

    The mesh supervisor reports its failure as a JSON ``mesh_failure`` event
    whose ``error`` is the cause, followed by JSON events of its cleanup. A
    start that fails before the supervisor runs, such as a start check that
    refuses it, ends with a plain text line. systemd's own messages about the
    unit are not the unit's processes and are not read.
    """
    output = call(["journalctl", "_SYSTEMD_UNIT=" + unit, "-b", "--no-pager", "-o", "cat", "-n", "200"],
                  run=run, accepted=(0, 1)).stdout
    text = error = None
    for line in reversed(output.splitlines()):
        line = line.strip()
        if not line:
            continue
        try:
            event = json.loads(line) if line.startswith("{") else None
        except ValueError:
            event = None
        if isinstance(event, dict):
            if event.get("event") == "mesh_failure" and event.get("error"):
                # A plain line newer than the failure belongs to a later start.
                return (text or str(event["error"]))[:ERROR_TEXT]
            error = error or (str(event["error"]) if event.get("error") else None)
        else:
            text = text or line
    value = text or error
    return value[:ERROR_TEXT] if value else None


def mesh_report(*, root="/", run=subprocess.run):
    """The SparkRing mesh units of this four-Spark ring member and its marker processes.

    Returns ``{"active", "failed", "markers"}``: the names of active mesh
    units; each failed unit with systemd's ``result`` (``exit-code`` after the
    supervisor's own orderly stop or a failed start; ``watchdog``, ``signal``
    or ``core-dump`` when the supervisor process was lost) and ``error``, its
    last logged error line (``last_error``); and the PIDs of running marker
    processes. Markers while no mesh unit is active were left by a supervisor
    that ended without stopping them.
    """
    listing = call(["systemctl", "list-units", "--type=service", "--all", "--no-legend", "--plain",
                    *MESH_UNIT_PATTERNS], run=run).stdout
    active, failed = [], []
    for line in listing.splitlines():
        fields = line.split()
        if fields and fields[0] in ("●", "*", "x"):
            fields = fields[1:]
        if len(fields) < 3:
            continue
        unit, state = fields[0], fields[2]
        if state == "active":
            active.append(unit)
        elif state == "failed":
            result = call(["systemctl", "show", "-p", "Result", "--value", unit], run=run).stdout.strip()
            failed.append({"unit": unit, "result": result or None, "error": last_error(unit, run=run)})
    return {"active": active, "failed": failed, "markers": marker_processes(root=root)}


def mesh_failure_text(row):
    """``UNIT failed: ERROR`` for one failed unit of ``mesh_report``."""
    return f"{row['unit']} failed: " + (row.get("error") or f"systemd result {row.get('result') or 'unknown'}")


def orphaned_markers(report):
    """Whether marker processes run on a Spark of ``mesh_report`` while none of its mesh units is active."""
    return bool(report) and bool(report.get("markers")) and not report.get("active")


def snapshot(*, root="/", collect=_collect_local, run=subprocess.run, now=time.time):
    """The ``sparkring-node-status/v1`` document of this Spark, as the agent records it every 30 seconds.

    A Spark with a recorded administration network adds ``control``
    (``control_report``) and a warning per tunnel peer without a recent
    handshake. A four-Spark ring member adds ``mesh`` (``mesh_report``); when
    the fabric check fails while a mesh unit has failed, the error names that
    unit and its last log line, and the ring check's finding becomes a warning.

    On a four-Spark ring, a ConnectX function whose restart failed in this
    boot and that carries the administration tunnel to other Sparks cuts
    their path to Node A; ``sudo sparkring hairpin`` cannot reach them, so the
    next action is then to reboot this Spark, whose next boot restarts no
    function (``hairpin.reboot_advice``).
    """
    result = {"schema": "sparkring-node-status/v1", "observed_at": now(), "hostname": socket.gethostname(),
              **observation_identity(root=root), "source": "host-agent",
              "hardware_qualified": False, "state": "not-configured", "next_action": "sparkring setup"}
    if not location(root, "/etc/sparkring/fabric.json").exists():
        return result
    warnings = []
    advice = None
    reads = (ValueError, KeyError, TypeError, OSError, RuntimeError, subprocess.SubprocessError)
    # Read on its own, so a failing fabric check still reports the tunnel.
    try:
        tunnel = control_report(root=root, run=run, now=now)
    except reads as error:
        tunnel = {"error": str(error)}
    if tunnel is not None:
        result["control"] = tunnel
        warnings += tunnel_problems(tunnel) if "error" not in tunnel else [
            "admin tunnel state unavailable: " + tunnel["error"]]
    try:
        config = read(root, "/etc/sparkring/fabric.json")
        result.update(rank=config["rank"], size=config["size"], cluster_id=config["cluster_id"])
        four = config["size"] == 4
        if four:
            from runtime.host import hairpin
            advice = hairpin.reboot_advice(root=root)
        if four:
            # Read before the fabric check, which a failed mesh can fail.
            try:
                result["mesh"] = mesh_report(root=root, run=run)
            except reads as error:
                result["mesh"] = {"error": str(error)}
            if orphaned_markers(result["mesh"]):
                warnings.append("mesh marker processes run while no mesh unit is active; the mesh's own cleanup "
                                "must stop them before the mesh starts again")
            warnings += mesh_units_without_start_check(root=root, run=run)
        elif location(root, "/etc/sparkring/hairpin.json").exists():
            warnings.append("hairpin approval on a Spark that is not in a four-Spark ring: "
                            "sudo sparkring node hairpin revoke")
        facts = observe(config, collect=collect)
        if four:
            # Checked before the fabric routes, the fabric service and the mesh:
            # a mesh that its start check refused then reports the root cause.
            check_hairpin(config, facts, warnings, root=root, run=run)
        verify_persistence(config, facts, run=run)
        if config.get("ownership") == "observed" and config.get("native_mesh"):
            from runtime.common import qwen_mesh
            mesh = config["native_mesh"]
            qwen_mesh.check(mesh["reference"], config["rank"], mesh["hcas"], 3, mesh["host_ip"])
        elif config.get("ownership") != "observed" and call(["systemctl", "is-active", "sparkring-fabric.service"], run=run, accepted=(0, 3)).returncode:
            raise ValueError("Fabric service is not active; inspect journalctl -u sparkring-fabric")
        result.update(state="network-configured", next_action="sparkring models",
                      containers=[{"name": c.get("name"), "state": c.get("state")} for c in (facts["docker"].get("containers") or [])],
                      model_ready=None)
        if config.get("ownership") == "observed":
            result["state"] = "existing-network-verified"
    except (ValueError, KeyError, OSError, RuntimeError, subprocess.SubprocessError) as error:
        text, action = str(error), advice or getattr(error, "next_action", None)
        failed = (result.get("mesh") or {}).get("failed") or []
        if failed and action is None:
            # A failed mesh unit is the cause of the ring check's missing
            # objects; its own log line says why it failed.
            warnings.append(text)
            text, action = mesh_failure_text(failed[0]), "journalctl -u " + failed[0]["unit"] + " -b"
        result.update(state="needs-attention", error=text, next_action=action or "sparkring status --refresh")
    if warnings:
        result["warnings"] = warnings
    return result


def status(*, root="/", now=time.time):
    try:
        result = read(root, "/run/sparkring/status.json")
    except FileNotFoundError:
        return {"state": "agent-unavailable", "next_action": "systemctl status sparkring-agent", "hardware_qualified": False}
    age = now() - result["observed_at"]
    result["age_seconds"] = round(age, 1)
    if age < -5 or age > 90:
        result.update(state="stale", next_action="systemctl status sparkring-agent")
    return result


def agent(*, root="/", once=False):
    while True:
        save(root, "/run/sparkring/status.json", snapshot(root=root))
        if once:
            return
        time.sleep(30)
