"""Generate C tests from the supplied offline route/numeric reference vectors.

Test generation only. The C library has no Python dependency.
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROLE = {"rocep1s0f0": 0, "roceP2p1s0f0": 1, "rocep1s0f1": 2, "roceP2p1s0f1": 3}


def ints(key):
    return [int(v) for v in re.findall(r"=(-?\d+)", key)]


def brace(values):
    return "{" + ",".join(str(v) for v in values) + "}"


def cable(text):
    return brace(re.fullmatch(r"(\d+)\.port([01])-(\d+)\.port([01])", text).groups())


def generate():
    route_file, numeric_file = HERE / "routes.json", HERE / "numeric.json"
    routes, numeric = json.loads(route_file.read_text()), json.loads(numeric_file.read_text())
    out = ["/* Generated by generate_vectors.py from private supplied reference vectors.",
           " * routes.json SHA256 " + hashlib.sha256(route_file.read_bytes()).hexdigest(),
           " * numeric.json SHA256 " + hashlib.sha256(numeric_file.read_bytes()).hexdigest() + " */"]

    def array(name, typename, rows):
        out.extend([f"static const {typename} {name}[] = {{", *[f"  {row}," for row in rows], "};"])

    out += ["typedef struct { const char *name; int cable_count; sircl_cable cables[16]; int world; int positions[16]; int lanes, start, count; const char *texts[16]; } layout_vector;",
            "typedef struct { int rank, peer, lane, local_role, remote_role, hops; sircl_fabric_step steps[16]; } lane_vector;"]
    layouts, all_lanes = [], []
    for name, entry in routes.items():
        first = len(all_lanes)
        for rank in entry["ranks"]:
            for peer, lanes in rank["lanes"].items():
                for lane in lanes:
                    all_lanes.append(brace([rank["rank"], peer, lane["lane"], ROLE[lane["local"]],
                                            ROLE[lane["remote"]], lane["hops"], brace(cable(c) for c in lane["cables"])]))
        layouts.append(brace([json.dumps(name), len(entry["cables"]), brace(cable(c) for c in entry["cables"]),
                              len(entry["rank_positions"]), brace(entry["rank_positions"]), entry["lanes"], first,
                              len(all_lanes)-first, brace(json.dumps(r["route_text"]) for r in entry["ranks"])]))
    array("route_layouts", "layout_vector", layouts)
    array("route_lanes", "lane_vector", all_lanes)
    out += ["typedef struct { int kind; uint64_t packs; int parts, index; uint64_t first, count; } range_vector;"]
    ranges = []
    for kind, name in enumerate(("stripe", "chunk")):
        for key, entries in numeric[name].items():
            packs, parts = ints(key)
            for index, (first, count) in enumerate(entries):
                ranges.append(brace([kind, packs, parts, index, first, count]))
    array("numeric_ranges", "range_vector", ranges)
    out += ["typedef struct { int ns, source, slot, lane, world, lanes; uint32_t expected; } flag_vector;"]
    array("numeric_flags", "flag_vector", [brace([*ints(k), str(v)+"u"]) for k, v in numeric["flag_index"].items()])
    out += ["typedef struct { int op; uint32_t bytes, expected; } op_vector;"]
    array("numeric_ops", "op_vector", [brace([*ints(k), str(v)+"u"]) for k, v in numeric["op_word"].items()])
    out += ["typedef struct { sircl_phase phase; uint32_t expected; } descriptor_vector;"]
    array("numeric_descriptors", "descriptor_vector", [brace([brace(ints(k)), str(v)+"u"]) for k, v in numeric["descriptor"].items()])
    out += ["typedef struct { int world, rank; int peers[16]; } post_vector;"]
    array("numeric_posting", "post_vector", [brace([ints(k)[0], rank, brace(order)]) for k, ranks in numeric["ring_farthest"].items() for rank, order in ranks.items()])
    out += ["typedef struct { int world; int owners[16], phase_count; } owner_vector;",
            "typedef struct { int world, rank, phase_index; sircl_phase phase; } phase_vector;"]
    owners, phases = [], []
    for key, entry in numeric["swing"].items():
        world = ints(key)[0]
        owners.append(brace([world, brace(entry["chunk_owners"]), len(entry["phases"]["0"])]))
        for rank, rank_phases in entry["phases"].items():
            for index, (peer, first, end, ns) in enumerate(rank_phases):
                phases.append(brace([world, rank, index, brace([first, end, peer, ns])]))
    array("numeric_owners", "owner_vector", owners)
    array("numeric_phases", "phase_vector", phases)
    out += ["typedef struct { int world; uint64_t swing_above, bytes; int algorithm; } selection_vector;"]
    array("numeric_selection", "selection_vector", [brace([*ints(k), {"oneshot":0,"twoshot":1,"swing":2}[v]]) for k, v in numeric["select_algorithm"].items()])
    (HERE / "reference_vectors.h").write_text("\n".join(out) + "\n", encoding="utf-8")


if __name__ == "__main__":
    generate()
