"""Render performance/enhancements.md, the per-model view of the enhancement catalog.

The catalog, performance/enhancements.json, is the authored source; the
Markdown view is generated from it and never edited by hand. ``--check``
validates the catalog (scripts/check_enhancements.py ``validate``, including
each entry's list of profiles that turn it on) and fails when the view
differs from what the catalog renders; scripts/check_repository_layout.py
runs it.
"""

from __future__ import annotations

import argparse
import json
import posixpath
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts import check_enhancements as catalog_check  # noqa: E402

VIEW = "performance/enhancements.md"
HERE = posixpath.dirname(VIEW)


def cell(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def code(text: str) -> str:
    return "`" + str(text).replace("`", "'") + "`"


def sizes(values) -> str:
    return "any" if values == "any" else "/".join(str(value) for value in values)


def parallelism_text(parallelism: dict) -> str:
    parts = []
    for rule in parallelism["supported"]:
        text = sizes(rule["tp"])
        if rule["dcp"] != "any":
            text += f" (DCP {sizes(rule['dcp'])})"
        parts.append(text)
    for rule in parallelism.get("refused", []):
        text = f"refused at {sizes(rule['tp'])}"
        if rule["dcp"] != "any":
            text += f" (DCP {sizes(rule['dcp'])})"
        parts.append(text)
    return "; ".join(parts)


def enable_markdown(enable: dict) -> str:
    parts = [code(f"{key}={value}") for key, value in enable.get("environment", {}).items()]
    for flag, value in enable.get("arguments", {}).items():
        parts.append(code(flag if value is True else f"{flag} {value}"))
    if enable.get("speculative"):
        parts.append(code("--speculative-config") + " keys " + code(json.dumps(enable["speculative"],
                                                                              separators=(",", ":"))))
    for key in ("checkpoint", "launcher", "plugin", "host", "note"):
        if enable.get(key):
            parts.append(("host: " if key == "host" else "") + enable[key])
    return cell("; ".join(parts))


def availability(entry: dict, images: dict) -> str:
    source = entry["provided_by"]
    if source.get("host"):
        return "host setting"
    listed = source.get("images", [])
    if not listed:
        return "needs a port"
    if "any" in listed:
        return "any image"
    return "from " + ", ".join(images[key]["label"] for key in listed)


def reference(path: str) -> str:
    """A link for a repository file, plain text for a private record or a source reference."""
    if path.startswith(("private record ", "source: ")):
        return cell(path)
    target = path.split("#", 1)[0]
    return f"[{cell(target)}]({posixpath.relpath(target, HERE)})"


def model_order(catalog: dict, root: Path) -> list[str]:
    names = list(dict.fromkeys(catalog_check.model_names(root).values()))
    used = {record["name"] for entry in catalog["enhancements"] for record in entry["models"]}
    used |= {name for item in catalog["not_adopted"] for name in item["models"]}
    return [name for name in names if name in used]


def model_rows(catalog: dict, name: str) -> list[tuple]:
    rows = []
    for entry in catalog["enhancements"]:
        for record in entry["models"]:
            if record["name"] != name:
                continue
            gain = record.get("gain") or entry.get("gain")
            percent = gain.get("percent") if gain else None
            scope = ""
            if record.get("checkpoints"):
                scope = " (" + ", ".join(pattern.split("/")[-1] for pattern in record["checkpoints"]) + ")"
            rows.append((percent is None, -(percent or 0), entry["id"], entry, record, gain, scope))
    rows.sort(key=lambda row: row[:3])
    return rows


def render(catalog: dict, root: Path = catalog_check.ROOT) -> str:
    images = catalog["images"]
    lines = [
        "# Enhancements by model",
        "",
        "<!-- Generated by scripts/generate_enhancements.py from performance/enhancements.json; do not edit. -->",
        "",
        "Every speed, memory and startup enhancement a SparkRing deployment can enable, per model: what it "
        "changes, the tensor-parallel (TP) sizes it runs at, how to turn it on, its measured gain and its "
        "status. The [catalog](enhancements.json) holds each entry once, with every measurement's conditions "
        "and evidence; edit it and run `python scripts/generate_enhancements.py` to regenerate this page.",
        "",
        "Check a deployment against the catalog (OFFLINE; reads repository files and the files named):",
        "",
        "```bash",
        "python scripts/check_enhancements.py PROFILE",
        "python scripts/check_enhancements.py PROFILE --plan RUN/plan.json --arm S+ --enabled host-sm-clock-lock",
        "python scripts/check_enhancements.py PROFILE --env-dump env.txt --args-dump args.json --tp 8 --dcp 4 \\",
        "  --image dev-20261008-kraken-csf-sircl-libsircl-cu1342-nccl2323-status034",
        "```",
        "",
        "The checker marks each applicable entry `enabled`, `missing`, `refused-here` or `needs-port` "
        "(the deployment's image does not carry it) and sorts the missing ones by measured gain. Gains are "
        "relative to the same deployment without the entry, under the conditions stated; a gain measured on "
        "one model, size or image is not a result for another. \"Private record\" marks evidence kept outside "
        "the repository, named by date and label. A workspace plugin is a vLLM general plugin from a private "
        "eight-Spark research workspace, written for image `aba309e4610c` and not in this repository; the "
        "catalog records its effect and switches, not its code. Status values: "
        + "; ".join(f"`{key}`, {meaning}" for key, meaning in catalog["statuses"].items()) + ".",
        "",
        "## Images",
        "",
        "An entry carried by an image is carried by the images built on it.",
        "",
        "| Image | ID | Built on | Transports | Contents |",
        "|---|---|---|---|---|",
    ]
    for key, image in images.items():
        name = f"[{code(key)}]({posixpath.relpath(image['release'], HERE)})" if image["release"] else code(key)
        parent = images[image["parent"]]["label"] if image["parent"] else "—"
        lines.append(f"| {image['label']}<br>{name} | {code(image['short_id']) if image['short_id'] else '—'} | "
                     f"{parent} | {', '.join(image['transports'])} | {cell(image['description'])} |")
    for name in model_order(catalog, root):
        rows = model_rows(catalog, name)
        lines += ["", f"## {name}", ""]
        if rows:
            lines += ["| Enhancement | Side | TP | How to enable | Gain | Status |", "|---|---|---|---|---|---|"]
            for _, _, key, entry, record, gain, scope in rows:
                status = record.get("status") or entry["status"]
                lines.append(
                    f"| [{cell(entry['title'])}](#{key}){cell(scope)} | {', '.join(entry['sides'])} | "
                    f"{parallelism_text(entry['parallelism'])} | {enable_markdown(entry['enable'])} | "
                    f"{cell(gain['summary']) if gain else 'not measured for this model'} | {status}; "
                    f"{availability(entry, images)} |")
        rejected = [item for item in catalog["not_adopted"] if name in item["models"]]
        if rejected:
            lines += ["", "Measured without a gain, not adopted:", ""]
            for item in rejected:
                lines.append(f"- {item['title']} ({item['setting']}): {item['result']}. Evidence: "
                             + "; ".join(reference(path) for path in item["evidence"]) + ".")
    lines += ["", "## Entry reference", ""]
    for entry in catalog["enhancements"]:
        models = ", ".join(dict.fromkeys(record["name"] for record in entry["models"]))
        lines += [f"### {code(entry['id'])}", "",
                  f"**{entry['title']}.** {entry['description']}", "",
                  f"- Category: {catalog['categories'][entry['category']]}.",
                  f"- Models: {models}. Sizes: {parallelism_text(entry['parallelism'])}.",
                  f"- Availability: {availability(entry, images)}"
                  + (f". Port: {entry['provided_by']['port']}" if entry["provided_by"].get("port") else "") + "."]
        for rule in entry["parallelism"].get("refused", []):
            lines.append(f"- Refused at TP {sizes(rule['tp'])}"
                         + (f", DCP {sizes(rule['dcp'])}" if rule["dcp"] != "any" else "")
                         + f" by {rule['by']}: \"{rule['text']}\".")
        if entry.get("requires"):
            lines.append("- Requires: " + ", ".join(f"[{code(other)}](#{other})" for other in entry["requires"]) + ".")
        if entry.get("superseded_by"):
            lines.append(f"- Superseded for eligible batches by [{code(entry['superseded_by'])}]"
                         f"(#{entry['superseded_by']}) when that is on.")
        if entry.get("trade_off"):
            lines.append(f"- Trade-off: {entry['trade_off']}.")
        lines.append("- Profiles that turn it on: "
                     + (", ".join(code(profile) for profile in entry["profiles"]) or "none") + ".")
        for measurement in entry["measurements"]:
            conditions = [f"TP{measurement['tp']}" + (f"/DCP{measurement['dcp']}" if measurement["dcp"] else "")
                          if measurement["tp"] else None,
                          f"{measurement['streams']} streams" if measurement["streams"] else None,
                          f"context {measurement['context']}" if measurement["context"] else None,
                          measurement.get("checkpoint"),
                          f"image {images[measurement['image']]['label'] if measurement['image'] in images else measurement['image']}"
                          if measurement["image"] else None]
            lines.append("- Measured (" + ", ".join(item for item in conditions if item) + "): "
                         + f"{measurement['result']}. Evidence: {reference(measurement['evidence'])}.")
        lines.append("- Evidence: " + "; ".join(reference(path) for path in entry["evidence"]) + ".")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def generate(check: bool = False, root: Path = catalog_check.ROOT) -> int:
    """Write (or with ``check``, verify) the view; returns the number of catalog entries."""
    catalog = catalog_check.load_catalog(root)
    problems = catalog_check.validate(catalog, root)
    if problems:
        raise ValueError(f"{catalog_check.CATALOG}: " + "; ".join(problems))
    text = render(catalog, root)
    path = root / VIEW
    current = path.read_bytes().replace(b"\r\n", b"\n") if path.is_file() else b""
    if current != text.encode("utf-8"):
        if check:
            raise ValueError(f"{VIEW} is stale; run python scripts/generate_enhancements.py")
        path.write_bytes(text.encode("utf-8"))
    return len(catalog["enhancements"])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if the catalog is invalid or the view is stale")
    args = parser.parse_args(argv)
    try:
        count = generate(args.check)
    except (ValueError, OSError, KeyError) as error:
        print(error, file=sys.stderr)
        return 1
    print(f"{'Checked' if args.check else 'Wrote'} {VIEW} from {count} enhancements")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
